import type {
  ExerciseTrackingType,
  StructuredExerciseInput,
  TrainingGoalType,
  UnilateralMode,
} from "@/lib/types";

export type ExerciseCategory =
  | "mobility"
  | "strength"
  | "cardio"
  | "core"
  | "running_prep"
  | "recovery"
  | "athletic";

export type MovementPattern =
  | "squat"
  | "hinge"
  | "lunge"
  | "push"
  | "pull"
  | "carry"
  | "core"
  | "mobility"
  | "run"
  | "walk"
  | "calf"
  | "lateral"
  | "power";

export type DifficultyTier = "intro" | "foundation" | "intermediate";

export type CautionTag =
  | "knee"
  | "back"
  | "shoulder"
  | "ankle"
  | "hamstring"
  | "impact"
  | "overhead"
  | "loaded_spine";

export type ExerciseTrackingMetadata = {
  trackingType: ExerciseTrackingType;
  unilateralMode: UnilateralMode;
  loadUnit: "lb" | "kg" | null;
  supportedLoadUnits: Array<"lb" | "kg">;
  distanceUnit: "mi" | "km" | "m" | null;
  supportedDistanceUnits: Array<"mi" | "km" | "m">;
  primaryValueLabel: string | null;
  secondaryValueLabel: string | null;
};

export type ExerciseCatalogItem = StructuredExerciseInput &
  ExerciseTrackingMetadata & {
    id: string;
    category: ExerciseCategory;
    movementPattern: MovementPattern;
    equipmentTags: string[];
    goalTags: TrainingGoalType[];
    difficultyTier: DifficultyTier;
    cautionTags: CautionTag[];
    traitTags: string[];
    preferenceTags: string[];
  };

export const exerciseCategories: Array<{
  value: ExerciseCategory;
  label: string;
}> = [
  { value: "mobility", label: "Mobility" },
  { value: "strength", label: "Strength" },
  { value: "cardio", label: "Cardio" },
  { value: "core", label: "Core" },
  { value: "running_prep", label: "Running prep" },
  { value: "recovery", label: "Recovery" },
  { value: "athletic", label: "Athletic" },
];

const completionMetadata: ExerciseTrackingMetadata = {
  trackingType: "completion",
  unilateralMode: "bilateral",
  loadUnit: null,
  supportedLoadUnits: [],
  distanceUnit: null,
  supportedDistanceUnits: [],
  primaryValueLabel: "Completion",
  secondaryValueLabel: null,
};

const repsMetadata = (
  unilateralMode: UnilateralMode = "bilateral",
): ExerciseTrackingMetadata => ({
  trackingType: "reps_only",
  unilateralMode,
  loadUnit: null,
  supportedLoadUnits: [],
  distanceUnit: null,
  supportedDistanceUnits: [],
  primaryValueLabel: "Reps",
  secondaryValueLabel: null,
});

const weightRepsMetadata = (
  unilateralMode: UnilateralMode = "bilateral",
  labels: { primaryValueLabel?: string; secondaryValueLabel?: string } = {},
): ExerciseTrackingMetadata => ({
  trackingType: "weight_reps",
  unilateralMode,
  loadUnit: "lb",
  supportedLoadUnits: ["lb", "kg"],
  distanceUnit: null,
  supportedDistanceUnits: [],
  primaryValueLabel: labels.primaryValueLabel ?? "Load",
  secondaryValueLabel: labels.secondaryValueLabel ?? "Reps",
});

const durationMetadata = (
  unilateralMode: UnilateralMode = "bilateral",
): ExerciseTrackingMetadata => ({
  trackingType: "duration",
  unilateralMode,
  loadUnit: null,
  supportedLoadUnits: [],
  distanceUnit: null,
  supportedDistanceUnits: [],
  primaryValueLabel: "Duration",
  secondaryValueLabel: null,
});

const distanceMetadata = (
  unilateralMode: UnilateralMode = "bilateral",
  unit: "mi" | "km" | "m" = "m",
): ExerciseTrackingMetadata => ({
  trackingType: "distance",
  unilateralMode,
  loadUnit: null,
  supportedLoadUnits: [],
  distanceUnit: unit,
  supportedDistanceUnits: ["m", "km", "mi"],
  primaryValueLabel: "Distance",
  secondaryValueLabel: null,
});

const distanceDurationMetadata: ExerciseTrackingMetadata = {
  trackingType: "distance_duration",
  unilateralMode: "bilateral",
  loadUnit: null,
  supportedLoadUnits: [],
  distanceUnit: "mi",
  supportedDistanceUnits: ["mi", "km", "m"],
  primaryValueLabel: "Distance",
  secondaryValueLabel: "Duration",
};

const allStrengthGoals: TrainingGoalType[] = [
  "general_fitness",
  "strength",
  "hypertrophy",
  "sport_performance",
];

const simpleGoals: TrainingGoalType[] = [
  "recovery",
  "consistency",
  "general_fitness",
];

const exerciseCatalogBase = [
  {
    id: "bodyweight-squat",
    name: "Bodyweight squat",
    category: "strength",
    movementPattern: "squat",
    equipmentTags: ["Bodyweight"],
    goalTags: [...simpleGoals, "strength"],
    difficultyTier: "intro",
    cautionTags: ["knee"],
    traitTags: ["bilateral", "low_setup"],
    preferenceTags: ["bodyweight", "lower body", "squat"],
    sets: 3,
    reps: "8-10",
    rest: "60 sec",
    coachingNote:
      "Keep your ribs stacked and move through a comfortable range.",
    videoUrl: "https://www.youtube.com/watch?v=aclHkVaku9U",
  },
  {
    id: "box-squat",
    name: "Box squat",
    category: "recovery",
    movementPattern: "squat",
    equipmentTags: ["Bodyweight", "Bench"],
    goalTags: ["recovery", "consistency", "general_fitness"],
    difficultyTier: "intro",
    cautionTags: ["knee"],
    traitTags: ["bilateral", "low_load"],
    preferenceTags: ["bodyweight", "lower body", "squat"],
    sets: 2,
    reps: "6-8",
    rest: "60 sec",
    coachingNote: "Sit back to a comfortable height and stand up with control.",
  },
  {
    id: "goblet-squat",
    name: "Goblet squat",
    category: "strength",
    movementPattern: "squat",
    equipmentTags: ["Dumbbells", "Kettlebell"],
    goalTags: allStrengthGoals,
    difficultyTier: "foundation",
    cautionTags: ["knee", "back"],
    traitTags: ["bilateral", "loaded"],
    preferenceTags: ["dumbbells", "kettlebell", "lower body", "squat"],
    sets: 3,
    reps: "8-10",
    rest: "90 sec",
    coachingNote:
      "Hold the weight close and keep your knees tracking over your toes.",
    videoUrl: "https://www.youtube.com/watch?v=MeIiIdhvXT4",
  },
  {
    id: "barbell-back-squat",
    name: "Barbell back squat",
    category: "strength",
    movementPattern: "squat",
    equipmentTags: ["Barbell"],
    goalTags: ["strength", "sport_performance"],
    difficultyTier: "intermediate",
    cautionTags: ["knee", "back", "loaded_spine"],
    traitTags: ["bilateral", "higher_load"],
    preferenceTags: ["barbell", "lower body", "squat"],
    sets: 4,
    reps: "4-6",
    rest: "2-3 min",
    coachingNote: "Brace before each rep and keep the bar path controlled.",
  },
  {
    id: "romanian-deadlift",
    name: "Barbell Romanian deadlift",
    category: "strength",
    movementPattern: "hinge",
    equipmentTags: ["Barbell"],
    goalTags: allStrengthGoals,
    difficultyTier: "foundation",
    cautionTags: ["back", "hamstring"],
    traitTags: ["bilateral", "loaded"],
    preferenceTags: ["barbell", "hinge", "posterior chain"],
    sets: 3,
    reps: "8",
    rest: "90 sec",
    coachingNote:
      "Hinge at the hips with a barbell held close to your legs, keeping the bar path controlled throughout each rep.",
    videoUrl: "https://www.youtube.com/watch?v=JCXUYuzwNrM",
  },
  {
    id: "hip-hinge-drill",
    name: "Hip hinge drill",
    category: "recovery",
    movementPattern: "hinge",
    equipmentTags: ["Bodyweight"],
    goalTags: ["recovery", "consistency", "general_fitness"],
    difficultyTier: "intro",
    cautionTags: ["back", "hamstring"],
    traitTags: ["low_load", "technique"],
    preferenceTags: ["bodyweight", "hinge", "posterior chain"],
    sets: 2,
    reps: "8",
    rest: "45 sec",
    coachingNote:
      "Practice the hinge slowly and stop before your back takes over.",
  },
  {
    id: "glute-bridge",
    name: "Glute bridge",
    category: "recovery",
    movementPattern: "hinge",
    equipmentTags: ["Bodyweight", "Bands"],
    goalTags: [
      "recovery",
      "general_fitness",
      "running",
      "hypertrophy",
      "consistency",
    ],
    difficultyTier: "intro",
    cautionTags: [],
    traitTags: ["low_load", "posterior_chain"],
    preferenceTags: ["bodyweight", "glutes", "lower body"],
    sets: 3,
    reps: "10-12",
    rest: "60 sec",
    coachingNote: "Pause at the top and keep your low back quiet.",
    videoUrl: "https://www.youtube.com/watch?v=wPM8icPu6H8",
  },
  {
    id: "reverse-lunge",
    name: "Reverse lunge",
    category: "strength",
    movementPattern: "lunge",
    equipmentTags: ["Bodyweight", "Dumbbells"],
    goalTags: [
      "general_fitness",
      "strength",
      "hypertrophy",
      "sport_performance",
    ],
    difficultyTier: "foundation",
    cautionTags: ["knee"],
    traitTags: ["unilateral", "lower_body"],
    preferenceTags: ["bodyweight", "dumbbells", "lower body", "lunge"],
    sets: 3,
    reps: "8 each side",
    rest: "75 sec",
    coachingNote: "Step back softly and keep the front foot grounded.",
  },
  {
    id: "step-up",
    name: "Step-up",
    category: "strength",
    movementPattern: "lunge",
    equipmentTags: ["Bodyweight", "Dumbbells", "Bench"],
    goalTags: ["general_fitness", "strength", "running", "sport_performance"],
    difficultyTier: "foundation",
    cautionTags: ["knee"],
    traitTags: ["unilateral", "lower_body"],
    preferenceTags: ["bodyweight", "dumbbells", "lower body", "running prep"],
    sets: 3,
    reps: "8 each side",
    rest: "75 sec",
    coachingNote: "Use a low step and control the lowering phase.",
  },
  {
    id: "walking-lunge",
    name: "Walking lunge",
    category: "running_prep",
    movementPattern: "lunge",
    equipmentTags: ["Bodyweight", "Dumbbells"],
    goalTags: ["running", "sport_performance", "general_fitness"],
    difficultyTier: "foundation",
    cautionTags: ["knee"],
    traitTags: ["unilateral", "running_support"],
    preferenceTags: ["bodyweight", "dumbbells", "lower body", "running prep"],
    sets: 2,
    reps: "8 each side",
    rest: "75 sec",
    coachingNote: "Step smoothly and keep the front foot grounded.",
    videoUrl: "https://www.youtube.com/watch?v=L8fvypPrzzs",
  },
  {
    id: "incline-push-up",
    name: "Incline push-up",
    category: "strength",
    movementPattern: "push",
    equipmentTags: ["Bodyweight", "Bench"],
    goalTags: [
      "recovery",
      "general_fitness",
      "strength",
      "hypertrophy",
      "consistency",
    ],
    difficultyTier: "intro",
    cautionTags: ["shoulder"],
    traitTags: ["upper_body", "low_load"],
    preferenceTags: ["bodyweight", "push", "upper body"],
    sets: 3,
    reps: "8-12",
    rest: "60 sec",
    coachingNote: "Use a height that lets you control every rep.",
  },
  {
    id: "push-up",
    name: "Push-up",
    category: "strength",
    movementPattern: "push",
    equipmentTags: ["Bodyweight"],
    goalTags: [
      "general_fitness",
      "strength",
      "hypertrophy",
      "sport_performance",
    ],
    difficultyTier: "foundation",
    cautionTags: ["shoulder"],
    traitTags: ["upper_body", "low_setup"],
    preferenceTags: ["bodyweight", "push", "upper body"],
    sets: 3,
    reps: "6-12",
    rest: "90 sec",
    coachingNote: "Keep a strong plank and leave a rep or two in reserve.",
  },
  {
    id: "dumbbell-floor-press",
    name: "Dumbbell floor press",
    category: "strength",
    movementPattern: "push",
    equipmentTags: ["Dumbbells"],
    goalTags: ["strength", "hypertrophy", "general_fitness"],
    difficultyTier: "foundation",
    cautionTags: ["shoulder"],
    traitTags: ["upper_body", "loaded"],
    preferenceTags: ["dumbbells", "push", "chest", "upper body"],
    sets: 3,
    reps: "8-10",
    rest: "90 sec",
    coachingNote:
      "Pause the upper arms lightly on the floor and press with control.",
  },
  {
    id: "dumbbell-shoulder-press",
    name: "Dumbbell shoulder press",
    category: "strength",
    movementPattern: "push",
    equipmentTags: ["Dumbbells"],
    goalTags: ["strength", "hypertrophy"],
    difficultyTier: "foundation",
    cautionTags: ["shoulder", "overhead"],
    traitTags: ["upper_body", "loaded"],
    preferenceTags: ["dumbbells", "push", "shoulders", "overhead"],
    sets: 3,
    reps: "8-10",
    rest: "90 sec",
    coachingNote:
      "Press without shrugging and stop if the shoulder feels irritated.",
  },
  {
    id: "band-row",
    name: "Band row",
    category: "strength",
    movementPattern: "pull",
    equipmentTags: ["Bands"],
    goalTags: [
      "recovery",
      "general_fitness",
      "strength",
      "hypertrophy",
      "consistency",
    ],
    difficultyTier: "intro",
    cautionTags: ["shoulder"],
    traitTags: ["upper_body", "low_load"],
    preferenceTags: ["bands", "pull", "upper body", "back"],
    sets: 3,
    reps: "10-12",
    rest: "60 sec",
    coachingNote: "Pull your elbows back and keep your shoulders relaxed.",
  },
  {
    id: "dumbbell-row",
    name: "Dumbbell row",
    category: "strength",
    movementPattern: "pull",
    equipmentTags: ["Dumbbells", "Bench"],
    goalTags: [
      "general_fitness",
      "strength",
      "hypertrophy",
      "sport_performance",
    ],
    difficultyTier: "foundation",
    cautionTags: ["shoulder", "back"],
    traitTags: ["upper_body", "loaded"],
    preferenceTags: ["dumbbells", "pull", "upper body", "back"],
    sets: 3,
    reps: "8-10 each side",
    rest: "90 sec",
    coachingNote: "Pull the elbow toward your hip and keep the torso steady.",
  },
  {
    id: "farmer-carry",
    name: "Farmer carry",
    category: "strength",
    movementPattern: "carry",
    equipmentTags: ["Dumbbells", "Kettlebell"],
    goalTags: ["strength", "sport_performance", "general_fitness"],
    difficultyTier: "foundation",
    cautionTags: ["back"],
    traitTags: ["loaded", "core", "grip"],
    preferenceTags: ["dumbbells", "kettlebell", "carry", "core"],
    sets: 3,
    reps: "20-30 steps",
    rest: "75 sec",
    coachingNote: "Walk tall and keep the ribs stacked over the pelvis.",
  },
  {
    id: "dead-bug",
    name: "Dead bug",
    category: "core",
    movementPattern: "core",
    equipmentTags: ["Bodyweight"],
    goalTags: [
      "recovery",
      "general_fitness",
      "running",
      "sport_performance",
      "consistency",
    ],
    difficultyTier: "intro",
    cautionTags: [],
    traitTags: ["core", "low_load"],
    preferenceTags: ["bodyweight", "core"],
    sets: 3,
    reps: "6 each side",
    rest: "45 sec",
    coachingNote: "Move slowly and keep your back gently anchored.",
    videoUrl: "https://www.youtube.com/watch?v=4XLEnwUr1d8",
  },
  {
    id: "side-plank",
    name: "Side plank",
    category: "core",
    movementPattern: "core",
    equipmentTags: ["Bodyweight"],
    goalTags: [
      "general_fitness",
      "running",
      "sport_performance",
      "consistency",
    ],
    difficultyTier: "foundation",
    cautionTags: ["shoulder"],
    traitTags: ["core", "lateral"],
    preferenceTags: ["bodyweight", "core"],
    sets: 2,
    reps: "20-30 sec each side",
    rest: "45 sec",
    coachingNote: "Keep a straight line from shoulder to ankle.",
    videoUrl: "https://www.youtube.com/watch?v=K2VljzCC16g",
  },
  {
    id: "bird-dog",
    name: "Bird dog",
    category: "core",
    movementPattern: "core",
    equipmentTags: ["Bodyweight"],
    goalTags: ["recovery", "general_fitness", "consistency"],
    difficultyTier: "intro",
    cautionTags: [],
    traitTags: ["core", "low_load"],
    preferenceTags: ["bodyweight", "core", "back-friendly"],
    sets: 2,
    reps: "6 each side",
    rest: "45 sec",
    coachingNote: "Reach long without letting the hips rotate.",
  },
  {
    id: "dumbbell-lateral-raise",
    name: "Dumbbell lateral raise",
    category: "strength",
    movementPattern: "push",
    equipmentTags: ["Dumbbells"],
    goalTags: ["hypertrophy"],
    difficultyTier: "foundation",
    cautionTags: ["shoulder"],
    traitTags: ["upper_body", "accessory"],
    preferenceTags: ["dumbbells", "shoulders", "hypertrophy"],
    sets: 3,
    reps: "12-15",
    rest: "60 sec",
    coachingNote: "Lift only to a comfortable height and control the lowering.",
  },
  {
    id: "dumbbell-curl",
    name: "Dumbbell curl",
    category: "strength",
    movementPattern: "pull",
    equipmentTags: ["Dumbbells"],
    goalTags: ["hypertrophy"],
    difficultyTier: "intro",
    cautionTags: [],
    traitTags: ["upper_body", "accessory"],
    preferenceTags: ["dumbbells", "arms", "hypertrophy"],
    sets: 3,
    reps: "10-15",
    rest: "60 sec",
    coachingNote: "Keep the upper arm still and squeeze each rep.",
  },
  {
    id: "calf-raise",
    name: "Calf raise",
    category: "running_prep",
    movementPattern: "calf",
    equipmentTags: ["Bodyweight", "Dumbbells"],
    goalTags: ["running", "general_fitness", "hypertrophy"],
    difficultyTier: "intro",
    cautionTags: ["ankle"],
    traitTags: ["lower_body", "running_support"],
    preferenceTags: ["bodyweight", "dumbbells", "calves", "running prep"],
    sets: 3,
    reps: "12-15",
    rest: "45 sec",
    coachingNote: "Rise with control and lower slowly.",
  },
  {
    id: "tibialis-raise",
    name: "Tibialis raise",
    category: "running_prep",
    movementPattern: "calf",
    equipmentTags: ["Bodyweight"],
    goalTags: ["running", "recovery"],
    difficultyTier: "intro",
    cautionTags: ["ankle"],
    traitTags: ["lower_body", "running_support"],
    preferenceTags: ["bodyweight", "shin", "running prep"],
    sets: 2,
    reps: "12-15",
    rest: "45 sec",
    coachingNote: "Lift the toes toward the shins without bouncing.",
  },
  {
    id: "half-kneeling-hip-flexor-stretch",
    name: "Half-kneeling hip flexor stretch",
    category: "mobility",
    movementPattern: "mobility",
    equipmentTags: ["Bodyweight"],
    goalTags: [
      "recovery",
      "general_fitness",
      "running",
      "sport_performance",
      "consistency",
    ],
    difficultyTier: "intro",
    cautionTags: [],
    traitTags: ["mobility", "low_load"],
    preferenceTags: ["bodyweight", "mobility", "hips"],
    sets: 2,
    reps: "20-30 sec each side",
    rest: "30 sec",
    coachingNote:
      "Use a comfortable range, keep a gentle posterior pelvic position, and stop if you feel sharp pain.",
  },
  {
    id: "thoracic-rotation",
    name: "Open-book thoracic rotation",
    category: "mobility",
    movementPattern: "mobility",
    equipmentTags: ["Bodyweight"],
    goalTags: [
      "recovery",
      "general_fitness",
      "sport_performance",
      "consistency",
    ],
    difficultyTier: "intro",
    cautionTags: [],
    traitTags: ["mobility", "upper_body"],
    preferenceTags: ["bodyweight", "mobility", "upper back"],
    sets: 2,
    reps: "6 each side",
    rest: "30 sec",
    coachingNote:
      "Lie on your side and rotate the top arm open through a comfortable upper-back range.",
  },
  {
    id: "ankle-rock",
    name: "Knee-to-wall ankle mobilization",
    category: "mobility",
    movementPattern: "mobility",
    equipmentTags: ["Bodyweight"],
    goalTags: ["recovery", "running", "sport_performance"],
    difficultyTier: "intro",
    cautionTags: ["ankle"],
    traitTags: ["mobility", "running_support"],
    preferenceTags: ["bodyweight", "mobility", "ankle", "running prep"],
    sets: 2,
    reps: "8 each side",
    rest: "30 sec",
    coachingNote:
      "Drive the knee toward the wall through a comfortable ankle range without forcing it.",
  },
  {
    id: "brisk-walk",
    name: "Brisk walk",
    category: "cardio",
    movementPattern: "walk",
    equipmentTags: ["Bodyweight"],
    goalTags: ["recovery", "general_fitness", "consistency", "running"],
    difficultyTier: "intro",
    cautionTags: [],
    traitTags: ["cardio", "low_setup", "low_impact"],
    preferenceTags: ["cardio", "walking", "outdoors", "bodyweight"],
    sets: 1,
    reps: "10-20 min",
    rest: "As needed",
    coachingNote: "Keep the pace conversational and stop if symptoms spike.",
  },
  {
    id: "low-impact-cardio-march",
    name: "Low-impact cardio march",
    category: "cardio",
    movementPattern: "walk",
    equipmentTags: ["Bodyweight"],
    goalTags: ["general_fitness", "consistency", "recovery"],
    difficultyTier: "intro",
    cautionTags: [],
    traitTags: ["cardio", "low_setup", "low_impact"],
    preferenceTags: ["cardio", "bodyweight", "home"],
    sets: 3,
    reps: "2 min",
    rest: "60 sec",
    coachingNote: "March tall and keep the effort easy to moderate.",
  },
  {
    id: "run-walk-intervals",
    name: "Run/walk intervals",
    category: "cardio",
    movementPattern: "run",
    equipmentTags: ["Bodyweight"],
    goalTags: ["running"],
    difficultyTier: "intro",
    cautionTags: ["impact", "knee", "ankle"],
    traitTags: ["running", "interval", "cardio"],
    preferenceTags: ["running", "cardio", "outdoors"],
    sets: 6,
    reps: "1 min easy run / 2 min walk",
    rest: "Walk recoveries",
    coachingNote: "Keep the run portions easy enough to finish with control.",
  },
  {
    id: "easy-run",
    name: "Easy run",
    category: "cardio",
    movementPattern: "run",
    equipmentTags: ["Bodyweight"],
    goalTags: ["running"],
    difficultyTier: "foundation",
    cautionTags: ["impact", "knee", "ankle"],
    traitTags: ["running", "cardio"],
    preferenceTags: ["running", "cardio", "outdoors"],
    sets: 1,
    reps: "15-25 min easy",
    rest: "As needed",
    coachingNote:
      "Stay at a conversational pace and finish feeling like you could do more.",
  },
  {
    id: "stride-drills",
    name: "Stride drills",
    category: "running_prep",
    movementPattern: "run",
    equipmentTags: ["Bodyweight"],
    goalTags: ["running", "sport_performance"],
    difficultyTier: "foundation",
    cautionTags: ["impact", "knee", "ankle", "hamstring"],
    traitTags: ["running", "speed", "athletic"],
    preferenceTags: ["running", "cardio", "sport"],
    sets: 4,
    reps: "15 sec relaxed stride",
    rest: "60-90 sec walk",
    coachingNote: "Keep these smooth, relaxed, and well below sprint effort.",
  },
  {
    id: "lateral-lunge",
    name: "Lateral lunge",
    category: "athletic",
    movementPattern: "lateral",
    equipmentTags: ["Bodyweight", "Dumbbells"],
    goalTags: ["sport_performance", "general_fitness", "strength"],
    difficultyTier: "foundation",
    cautionTags: ["knee"],
    traitTags: ["unilateral", "lateral", "athletic"],
    preferenceTags: ["sport", "lateral", "lower body"],
    sets: 3,
    reps: "8 each side",
    rest: "75 sec",
    coachingNote: "Shift side to side without letting the knee cave inward.",
  },
  {
    id: "lateral-shuffle",
    name: "Lateral shuffle",
    category: "athletic",
    movementPattern: "lateral",
    equipmentTags: ["Bodyweight"],
    goalTags: ["sport_performance"],
    difficultyTier: "foundation",
    cautionTags: ["knee", "ankle", "impact"],
    traitTags: ["lateral", "athletic", "cardio"],
    preferenceTags: ["sport", "lateral", "agility"],
    sets: 4,
    reps: "10-15 sec",
    rest: "45 sec",
    coachingNote: "Stay low and controlled rather than chasing speed.",
  },
  {
    id: "skater-hop",
    name: "Skater hop",
    category: "athletic",
    movementPattern: "power",
    equipmentTags: ["Bodyweight"],
    goalTags: ["sport_performance"],
    difficultyTier: "intermediate",
    cautionTags: ["knee", "ankle", "impact"],
    traitTags: ["unilateral", "lateral", "power", "athletic"],
    preferenceTags: ["sport", "lateral", "jumping", "power"],
    sets: 3,
    reps: "5 each side",
    rest: "75 sec",
    coachingNote: "Land softly and keep every rep crisp.",
  },
  {
    id: "front-squat",
    name: "Front squat",
    category: "strength",
    movementPattern: "squat",
    equipmentTags: ["Barbell"],
    goalTags: allStrengthGoals,
    difficultyTier: "intermediate",
    cautionTags: ["knee", "back", "loaded_spine"],
    traitTags: ["bilateral", "loaded"],
    preferenceTags: ["barbell", "lower body", "squat"],
    sets: 4,
    reps: "4-6",
    rest: "2-3 min",
    coachingNote:
      "Keep the elbows high enough to support the bar and brace before each rep.",
  },
  {
    id: "dumbbell-squat",
    name: "Dumbbell squat",
    category: "strength",
    movementPattern: "squat",
    equipmentTags: ["Dumbbells"],
    goalTags: allStrengthGoals,
    difficultyTier: "foundation",
    cautionTags: ["knee", "back"],
    traitTags: ["bilateral", "loaded"],
    preferenceTags: ["dumbbells", "lower body", "squat"],
    sets: 3,
    reps: "8-12",
    rest: "90 sec",
    coachingNote:
      "Hold one dumbbell in each hand at your sides and use a comfortable squat depth.",
  },
  {
    id: "leg-press",
    name: "Leg press",
    category: "strength",
    movementPattern: "squat",
    equipmentTags: ["Machine"],
    goalTags: ["strength", "hypertrophy", "general_fitness"],
    difficultyTier: "foundation",
    cautionTags: ["knee", "back"],
    traitTags: ["bilateral", "machine"],
    preferenceTags: ["machine", "lower body", "squat"],
    sets: 3,
    reps: "10-12",
    rest: "90 sec",
    coachingNote:
      "Keep your hips down on the pad and use a range you can control.",
  },
  {
    id: "leg-extension",
    name: "Leg extension",
    category: "strength",
    movementPattern: "squat",
    equipmentTags: ["Machine"],
    goalTags: ["hypertrophy", "general_fitness"],
    difficultyTier: "foundation",
    cautionTags: ["knee"],
    traitTags: ["machine", "accessory"],
    preferenceTags: ["machine", "quads", "hypertrophy"],
    sets: 3,
    reps: "10-15",
    rest: "60 sec",
    coachingNote:
      "Lift smoothly and avoid forcing the knee into painful ranges.",
  },
  {
    id: "split-squat",
    name: "Split squat",
    category: "strength",
    movementPattern: "lunge",
    equipmentTags: ["Bodyweight", "Dumbbells"],
    goalTags: allStrengthGoals,
    difficultyTier: "foundation",
    cautionTags: ["knee"],
    traitTags: ["unilateral", "lower_body"],
    preferenceTags: ["bodyweight", "dumbbells", "lower body", "lunge"],
    sets: 3,
    reps: "8 each side",
    rest: "75 sec",
    coachingNote: "Keep the stance steady and lower with control.",
  },
  {
    id: "bulgarian-split-squat",
    name: "Bulgarian split squat",
    category: "strength",
    movementPattern: "lunge",
    equipmentTags: ["Bodyweight", "Dumbbells", "Bench"],
    goalTags: ["strength", "hypertrophy", "sport_performance"],
    difficultyTier: "intermediate",
    cautionTags: ["knee"],
    traitTags: ["unilateral", "lower_body"],
    preferenceTags: ["dumbbells", "lower body", "lunge"],
    sets: 3,
    reps: "6-10 each side",
    rest: "90 sec",
    coachingNote:
      "Use a stable rear-foot support and keep the front foot grounded.",
  },
  {
    id: "forward-lunge",
    name: "Forward lunge",
    category: "strength",
    movementPattern: "lunge",
    equipmentTags: ["Bodyweight", "Dumbbells"],
    goalTags: ["general_fitness", "strength", "sport_performance"],
    difficultyTier: "foundation",
    cautionTags: ["knee"],
    traitTags: ["unilateral", "lower_body"],
    preferenceTags: ["bodyweight", "dumbbells", "lower body", "lunge"],
    sets: 3,
    reps: "8 each side",
    rest: "75 sec",
    coachingNote:
      "Step forward under control and push back from the front foot.",
  },
  {
    id: "conventional-deadlift",
    name: "Conventional deadlift",
    category: "strength",
    movementPattern: "hinge",
    equipmentTags: ["Barbell"],
    goalTags: ["strength", "sport_performance"],
    difficultyTier: "intermediate",
    cautionTags: ["back", "hamstring", "loaded_spine"],
    traitTags: ["bilateral", "higher_load"],
    preferenceTags: ["barbell", "hinge", "posterior chain"],
    sets: 3,
    reps: "3-5",
    rest: "2-3 min",
    coachingNote:
      "Brace hard, keep the bar close, and stop if position breaks down.",
  },
  {
    id: "trap-bar-deadlift",
    name: "Trap-bar deadlift",
    category: "strength",
    movementPattern: "hinge",
    equipmentTags: ["Trap bar"],
    goalTags: ["strength", "sport_performance", "general_fitness"],
    difficultyTier: "foundation",
    cautionTags: ["back", "loaded_spine"],
    traitTags: ["bilateral", "loaded"],
    preferenceTags: ["trap bar", "hinge", "lower body"],
    sets: 3,
    reps: "5-8",
    rest: "2 min",
    coachingNote:
      "Stand tall through the handles and keep the torso controlled.",
  },
  {
    id: "dumbbell-romanian-deadlift",
    name: "Dumbbell Romanian deadlift",
    category: "strength",
    movementPattern: "hinge",
    equipmentTags: ["Dumbbells"],
    goalTags: allStrengthGoals,
    difficultyTier: "foundation",
    cautionTags: ["back", "hamstring"],
    traitTags: ["bilateral", "loaded"],
    preferenceTags: ["dumbbells", "hinge", "posterior chain"],
    sets: 3,
    reps: "8-10",
    rest: "90 sec",
    coachingNote:
      "Hinge from the hips while the dumbbells travel close to your legs.",
  },
  {
    id: "hip-thrust",
    name: "Hip thrust",
    category: "strength",
    movementPattern: "hinge",
    equipmentTags: ["Barbell", "Bench"],
    goalTags: ["strength", "hypertrophy", "general_fitness"],
    difficultyTier: "foundation",
    cautionTags: ["back"],
    traitTags: ["bilateral", "loaded"],
    preferenceTags: ["barbell", "glutes", "posterior chain"],
    sets: 3,
    reps: "8-12",
    rest: "90 sec",
    coachingNote: "Keep the ribs down and pause briefly at the top.",
  },
  {
    id: "back-extension",
    name: "Back extension",
    category: "strength",
    movementPattern: "hinge",
    equipmentTags: ["Machine"],
    goalTags: ["general_fitness", "strength", "hypertrophy"],
    difficultyTier: "foundation",
    cautionTags: ["back", "hamstring"],
    traitTags: ["posterior_chain", "machine"],
    preferenceTags: ["posterior chain", "back", "glutes"],
    sets: 3,
    reps: "10-12",
    rest: "60 sec",
    coachingNote: "Move through the hips and avoid overextending at the top.",
  },
  {
    id: "seated-leg-curl",
    name: "Seated leg curl",
    category: "strength",
    movementPattern: "hinge",
    equipmentTags: ["Machine"],
    goalTags: ["hypertrophy", "general_fitness", "running"],
    difficultyTier: "foundation",
    cautionTags: ["hamstring", "knee"],
    traitTags: ["machine", "accessory"],
    preferenceTags: ["machine", "hamstrings", "hypertrophy"],
    sets: 3,
    reps: "10-15",
    rest: "60 sec",
    coachingNote: "Curl smoothly and control the return.",
  },
  {
    id: "barbell-bench-press",
    name: "Barbell bench press",
    category: "strength",
    movementPattern: "push",
    equipmentTags: ["Barbell", "Bench"],
    goalTags: ["strength", "hypertrophy"],
    difficultyTier: "intermediate",
    cautionTags: ["shoulder"],
    traitTags: ["upper_body", "higher_load"],
    preferenceTags: ["barbell", "chest", "push"],
    sets: 4,
    reps: "4-6",
    rest: "2-3 min",
    coachingNote: "Set the shoulders, touch under control, and press evenly.",
  },
  {
    id: "dumbbell-bench-press",
    name: "Dumbbell bench press",
    category: "strength",
    movementPattern: "push",
    equipmentTags: ["Dumbbells", "Bench"],
    goalTags: ["strength", "hypertrophy", "general_fitness"],
    difficultyTier: "foundation",
    cautionTags: ["shoulder"],
    traitTags: ["upper_body", "loaded"],
    preferenceTags: ["dumbbells", "chest", "push"],
    sets: 3,
    reps: "8-10",
    rest: "90 sec",
    coachingNote:
      "Lower with control and press without letting the shoulders pinch.",
  },
  {
    id: "incline-dumbbell-press",
    name: "Incline dumbbell press",
    category: "strength",
    movementPattern: "push",
    equipmentTags: ["Dumbbells", "Bench"],
    goalTags: ["hypertrophy", "strength", "general_fitness"],
    difficultyTier: "foundation",
    cautionTags: ["shoulder"],
    traitTags: ["upper_body", "loaded"],
    preferenceTags: ["dumbbells", "chest", "push", "incline"],
    sets: 3,
    reps: "8-12",
    rest: "90 sec",
    coachingNote:
      "Use a moderate incline and press through a comfortable path.",
  },
  {
    id: "incline-barbell-bench-press",
    name: "Incline barbell bench press",
    category: "strength",
    movementPattern: "push",
    equipmentTags: ["Barbell", "Bench"],
    goalTags: ["strength", "hypertrophy", "general_fitness"],
    difficultyTier: "intermediate",
    cautionTags: ["shoulder"],
    traitTags: ["upper_body", "loaded", "incline"],
    preferenceTags: ["barbell", "bench", "chest", "push", "incline"],
    sets: 3,
    reps: "6-10",
    rest: "2 min",
    coachingNote:
      "Use a moderate incline, keep both feet planted, lower the bar toward your upper chest with control, and press evenly without shrugging.",
    videoUrl: "https://www.youtube.com/watch?v=8YgkJN0gmNM",
  },
  {
    id: "close-grip-barbell-bench-press",
    name: "Close-grip barbell bench press",
    category: "strength",
    movementPattern: "push",
    equipmentTags: ["Barbell", "Bench"],
    goalTags: ["strength", "hypertrophy", "general_fitness"],
    difficultyTier: "foundation",
    cautionTags: ["shoulder"],
    traitTags: ["upper_body", "loaded", "compound", "triceps_focus"],
    preferenceTags: ["barbell", "bench", "triceps", "push", "upper body"],
    sets: 3,
    reps: "6-10",
    rest: "90-120 sec",
    coachingNote:
      "Use a grip around shoulder width, keep your feet planted, lower the bar with your elbows close to your sides, and press evenly.",
    videoUrl: "https://www.youtube.com/watch?v=OYoc93qAAEY",
  },
  {
    id: "machine-chest-press",
    name: "Machine chest press",
    category: "strength",
    movementPattern: "push",
    equipmentTags: ["Machine"],
    goalTags: ["hypertrophy", "general_fitness", "strength"],
    difficultyTier: "foundation",
    cautionTags: ["shoulder"],
    traitTags: ["upper_body", "machine"],
    preferenceTags: ["machine", "chest", "push"],
    sets: 3,
    reps: "8-12",
    rest: "90 sec",
    coachingNote:
      "Set the seat so the handles meet your mid-chest and press smoothly.",
  },
  {
    id: "barbell-overhead-press",
    name: "Barbell overhead press",
    category: "strength",
    movementPattern: "push",
    equipmentTags: ["Barbell"],
    goalTags: ["strength", "sport_performance"],
    difficultyTier: "intermediate",
    cautionTags: ["shoulder", "overhead", "back"],
    traitTags: ["upper_body", "loaded"],
    preferenceTags: ["barbell", "shoulders", "overhead"],
    sets: 3,
    reps: "5-8",
    rest: "2 min",
    coachingNote: "Brace before pressing and keep the bar path close.",
  },
  {
    id: "triceps-pushdown",
    name: "Triceps pushdown",
    category: "strength",
    movementPattern: "push",
    equipmentTags: ["Cable"],
    goalTags: ["hypertrophy", "general_fitness"],
    difficultyTier: "intro",
    cautionTags: ["shoulder"],
    traitTags: ["upper_body", "accessory"],
    preferenceTags: ["cable", "arms", "triceps"],
    sets: 3,
    reps: "10-15",
    rest: "60 sec",
    coachingNote: "Keep the elbows near your sides and move with control.",
  },
  {
    id: "seated-cable-row",
    name: "Seated cable row",
    category: "strength",
    movementPattern: "pull",
    equipmentTags: ["Cable"],
    goalTags: ["strength", "hypertrophy", "general_fitness"],
    difficultyTier: "foundation",
    cautionTags: ["shoulder", "back"],
    traitTags: ["upper_body", "loaded"],
    preferenceTags: ["cable", "back", "pull"],
    sets: 3,
    reps: "8-12",
    rest: "90 sec",
    coachingNote:
      "Sit tall, pull to the torso, and avoid leaning back to finish reps.",
  },
  {
    id: "chest-supported-row",
    name: "Chest-supported row",
    category: "strength",
    movementPattern: "pull",
    equipmentTags: ["Dumbbells", "Bench"],
    goalTags: ["strength", "hypertrophy", "general_fitness"],
    difficultyTier: "foundation",
    cautionTags: ["shoulder"],
    traitTags: ["upper_body", "supported"],
    preferenceTags: ["dumbbells", "back", "pull"],
    sets: 3,
    reps: "8-12",
    rest: "90 sec",
    coachingNote:
      "Keep the chest supported and pull the elbows back without shrugging.",
  },
  {
    id: "barbell-row",
    name: "Barbell row",
    category: "strength",
    movementPattern: "pull",
    equipmentTags: ["Barbell"],
    goalTags: ["strength", "hypertrophy"],
    difficultyTier: "intermediate",
    cautionTags: ["back", "shoulder"],
    traitTags: ["upper_body", "loaded"],
    preferenceTags: ["barbell", "back", "pull"],
    sets: 3,
    reps: "6-10",
    rest: "2 min",
    coachingNote: "Hold a stable hinge and row without jerking the torso.",
  },
  {
    id: "t-bar-row",
    name: "T-bar row",
    category: "strength",
    movementPattern: "pull",
    equipmentTags: ["Barbell", "Landmine", "Row handle"],
    goalTags: ["strength", "hypertrophy", "general_fitness"],
    difficultyTier: "foundation",
    cautionTags: ["back", "shoulder"],
    traitTags: ["upper_body", "loaded", "horizontal_pull"],
    preferenceTags: ["barbell", "landmine", "back", "pull", "gym"],
    sets: 3,
    reps: "8-12",
    rest: "90 sec",
    coachingNote:
      "Set your hips back, keep your torso steady, pull the handle toward your upper stomach, and lower the weight without jerking.",
    videoUrl: "https://www.youtube.com/watch?v=KDEl3AmZbVE",
  },
  {
    id: "lat-pulldown",
    name: "Lat pulldown",
    category: "strength",
    movementPattern: "pull",
    equipmentTags: ["Cable", "Machine"],
    goalTags: ["strength", "hypertrophy", "general_fitness"],
    difficultyTier: "foundation",
    cautionTags: ["shoulder"],
    traitTags: ["upper_body", "machine"],
    preferenceTags: ["cable", "machine", "back", "pull"],
    sets: 3,
    reps: "8-12",
    rest: "90 sec",
    coachingNote:
      "Pull the bar toward the upper chest and keep the neck relaxed.",
  },
  {
    id: "pull-up",
    name: "Pull-up",
    category: "strength",
    movementPattern: "pull",
    equipmentTags: ["Pull-up bar"],
    goalTags: ["strength", "sport_performance", "hypertrophy"],
    difficultyTier: "intermediate",
    cautionTags: ["shoulder"],
    traitTags: ["upper_body", "bodyweight"],
    preferenceTags: ["bodyweight", "back", "pull"],
    sets: 3,
    reps: "3-8",
    rest: "2 min",
    coachingNote:
      "Start from a controlled hang and stop before form breaks down.",
  },
  {
    id: "chin-up",
    name: "Chin-up",
    category: "strength",
    movementPattern: "pull",
    equipmentTags: ["Pull-up bar"],
    goalTags: [
      "strength",
      "hypertrophy",
      "general_fitness",
      "sport_performance",
    ],
    difficultyTier: "intermediate",
    cautionTags: ["shoulder"],
    traitTags: ["upper_body", "bodyweight", "vertical_pull"],
    preferenceTags: ["bodyweight", "back", "biceps", "pull", "pull-up bar"],
    sets: 3,
    reps: "3-8",
    rest: "2 min",
    coachingNote:
      "Use an underhand grip, start from a controlled hang, pull your chest toward the bar without swinging, and lower with control.",
    videoUrl: "https://www.youtube.com/watch?v=fNZ8Ty7jSFA",
  },
  {
    id: "assisted-pull-up",
    name: "Assisted pull-up",
    category: "strength",
    movementPattern: "pull",
    equipmentTags: ["Machine", "Bands", "Pull-up bar"],
    goalTags: ["strength", "hypertrophy", "general_fitness"],
    difficultyTier: "foundation",
    cautionTags: ["shoulder"],
    traitTags: ["upper_body", "assisted"],
    preferenceTags: ["bodyweight", "back", "pull"],
    sets: 3,
    reps: "5-8",
    rest: "90 sec",
    coachingNote: "Use enough assistance to control the full rep.",
  },
  {
    id: "face-pull",
    name: "Face pull",
    category: "strength",
    movementPattern: "pull",
    equipmentTags: ["Cable", "Bands"],
    goalTags: ["general_fitness", "hypertrophy", "sport_performance"],
    difficultyTier: "intro",
    cautionTags: ["shoulder"],
    traitTags: ["upper_body", "accessory"],
    preferenceTags: ["cable", "bands", "shoulders", "pull"],
    sets: 3,
    reps: "12-15",
    rest: "60 sec",
    coachingNote:
      "Pull toward the face with relaxed shoulders and controlled elbows.",
  },
  {
    id: "reverse-fly",
    name: "Reverse fly",
    category: "strength",
    movementPattern: "pull",
    equipmentTags: ["Dumbbells"],
    goalTags: ["hypertrophy", "general_fitness"],
    difficultyTier: "intro",
    cautionTags: ["shoulder"],
    traitTags: ["upper_body", "accessory"],
    preferenceTags: ["dumbbells", "rear delts", "pull"],
    sets: 3,
    reps: "12-15",
    rest: "60 sec",
    coachingNote:
      "Use light weights and move through a comfortable shoulder range.",
  },
  {
    id: "barbell-shrug",
    name: "Barbell shrug",
    category: "strength",
    movementPattern: "pull",
    equipmentTags: ["Barbell"],
    goalTags: ["strength", "hypertrophy", "general_fitness"],
    difficultyTier: "intro",
    cautionTags: ["shoulder"],
    traitTags: ["upper_body", "loaded", "accessory", "grip"],
    preferenceTags: ["barbell", "traps", "shoulders", "pull", "upper body"],
    sets: 3,
    reps: "8-12",
    rest: "60-90 sec",
    coachingNote:
      "Stand tall, lift your shoulders straight up without bending the elbows, pause briefly, and lower the bar with control.",
    videoUrl: "https://www.youtube.com/watch?v=9xGqgGFAtiM",
  },
  {
    id: "ez-bar-curl",
    name: "EZ-bar curl",
    category: "strength",
    movementPattern: "pull",
    equipmentTags: ["EZ bar"],
    goalTags: ["hypertrophy", "general_fitness", "strength"],
    difficultyTier: "intro",
    cautionTags: [],
    traitTags: ["upper_body", "loaded", "accessory"],
    preferenceTags: ["ez bar", "biceps", "arms", "pull", "hypertrophy"],
    sets: 3,
    reps: "8-12",
    rest: "60-90 sec",
    coachingNote:
      "Stand tall, keep your upper arms near your sides, curl the bar without swinging, and lower it slowly.",
    videoUrl: "https://www.youtube.com/watch?v=S_i3SEVgKWU",
  },
  {
    id: "chest-dip",
    name: "Chest dip",
    category: "strength",
    movementPattern: "push",
    equipmentTags: ["Dip bars"],
    goalTags: [
      "strength",
      "hypertrophy",
      "general_fitness",
      "sport_performance",
    ],
    difficultyTier: "intermediate",
    cautionTags: ["shoulder"],
    traitTags: ["upper_body", "bodyweight", "compound"],
    preferenceTags: ["bodyweight", "dip bars", "chest", "triceps", "push"],
    sets: 3,
    reps: "5-10",
    rest: "90 sec",
    coachingNote:
      "Support yourself on the bars, lean slightly forward, lower only as far as you can control comfortably, and press back up without bouncing.",
    videoUrl: "https://www.youtube.com/watch?v=4la6BkUBLgo",
  },
  {
    id: "hack-squat",
    name: "Hack squat",
    category: "strength",
    movementPattern: "squat",
    equipmentTags: ["Machine"],
    goalTags: ["strength", "hypertrophy", "general_fitness"],
    difficultyTier: "foundation",
    cautionTags: ["knee", "back"],
    traitTags: ["bilateral", "machine"],
    preferenceTags: ["machine", "lower body", "squat", "quads"],
    sets: 3,
    reps: "8-12",
    rest: "90-120 sec",
    coachingNote:
      "Set your feet securely, lower through a controlled range, and keep your hips and back supported.",
  },
  {
    id: "lying-leg-curl",
    name: "Lying leg curl",
    category: "strength",
    movementPattern: "hinge",
    equipmentTags: ["Machine"],
    goalTags: ["hypertrophy", "general_fitness", "running"],
    difficultyTier: "foundation",
    cautionTags: ["hamstring", "knee"],
    traitTags: ["machine", "accessory"],
    preferenceTags: ["machine", "hamstrings", "hypertrophy"],
    sets: 3,
    reps: "10-15",
    rest: "60-90 sec",
    coachingNote:
      "Keep the hips down on the pad and curl smoothly without swinging.",
  },
  {
    id: "seated-calf-raise",
    name: "Seated calf raise",
    category: "strength",
    movementPattern: "calf",
    equipmentTags: ["Machine"],
    goalTags: ["hypertrophy", "general_fitness", "running"],
    difficultyTier: "intro",
    cautionTags: ["ankle"],
    traitTags: ["machine", "accessory", "lower_body"],
    preferenceTags: ["machine", "calves", "hypertrophy"],
    sets: 3,
    reps: "10-15",
    rest: "60-90 sec",
    coachingNote:
      "Press through the balls of the feet and control the lowering phase.",
  },
  {
    id: "cable-fly",
    name: "Cable fly",
    category: "strength",
    movementPattern: "push",
    equipmentTags: ["Cable"],
    goalTags: ["hypertrophy", "general_fitness"],
    difficultyTier: "foundation",
    cautionTags: ["shoulder"],
    traitTags: ["upper_body", "accessory"],
    preferenceTags: ["cable", "chest", "hypertrophy"],
    sets: 3,
    reps: "10-15",
    rest: "60-90 sec",
    coachingNote:
      "Use a controlled arc and stop at a comfortable shoulder range.",
  },
  {
    id: "pec-deck",
    name: "Pec deck",
    category: "strength",
    movementPattern: "push",
    equipmentTags: ["Machine"],
    goalTags: ["hypertrophy", "general_fitness"],
    difficultyTier: "intro",
    cautionTags: ["shoulder"],
    traitTags: ["upper_body", "machine", "accessory"],
    preferenceTags: ["machine", "chest", "hypertrophy"],
    sets: 3,
    reps: "10-15",
    rest: "60-90 sec",
    coachingNote:
      "Set the seat for a comfortable chest-level path and bring the handles together smoothly.",
  },
  {
    id: "cable-lateral-raise",
    name: "Cable lateral raise",
    category: "strength",
    movementPattern: "push",
    equipmentTags: ["Cable"],
    goalTags: ["hypertrophy"],
    difficultyTier: "foundation",
    cautionTags: ["shoulder"],
    traitTags: ["upper_body", "accessory"],
    preferenceTags: ["cable", "shoulders", "hypertrophy"],
    sets: 3,
    reps: "10-15",
    rest: "60-90 sec",
    coachingNote:
      "Raise the cable through a comfortable side arc and control the return.",
  },
  {
    id: "hammer-curl",
    name: "Hammer curl",
    category: "strength",
    movementPattern: "pull",
    equipmentTags: ["Dumbbells"],
    goalTags: ["hypertrophy", "general_fitness"],
    difficultyTier: "intro",
    cautionTags: [],
    traitTags: ["upper_body", "accessory"],
    preferenceTags: ["dumbbells", "arms", "hypertrophy"],
    sets: 3,
    reps: "10-15",
    rest: "60-90 sec",
    coachingNote:
      "Keep a neutral grip and curl without swinging the upper arms.",
  },
  {
    id: "cable-overhead-triceps-extension",
    name: "Cable overhead triceps extension",
    category: "strength",
    movementPattern: "push",
    equipmentTags: ["Cable"],
    goalTags: ["hypertrophy", "general_fitness"],
    difficultyTier: "foundation",
    cautionTags: ["shoulder", "overhead"],
    traitTags: ["upper_body", "accessory"],
    preferenceTags: ["cable", "arms", "triceps"],
    sets: 3,
    reps: "10-15",
    rest: "60-90 sec",
    coachingNote:
      "Keep the ribs controlled and extend the elbows through a comfortable overhead range.",
  },
  {
    id: "hip-abduction-machine",
    name: "Hip abduction machine",
    category: "strength",
    movementPattern: "lateral",
    equipmentTags: ["Machine"],
    goalTags: ["hypertrophy", "general_fitness"],
    difficultyTier: "intro",
    cautionTags: [],
    traitTags: ["machine", "accessory", "lower_body"],
    preferenceTags: ["machine", "hips", "glutes", "hypertrophy"],
    sets: 3,
    reps: "10-15",
    rest: "60-90 sec",
    coachingNote:
      "Sit tall and move the legs outward with control instead of momentum.",
  },
  {
    id: "hip-adduction-machine",
    name: "Hip adduction machine",
    category: "strength",
    movementPattern: "lateral",
    equipmentTags: ["Machine"],
    goalTags: ["hypertrophy", "general_fitness"],
    difficultyTier: "intro",
    cautionTags: [],
    traitTags: ["machine", "accessory", "lower_body"],
    preferenceTags: ["machine", "hips", "adductors", "hypertrophy"],
    sets: 3,
    reps: "10-15",
    rest: "60-90 sec",
    coachingNote:
      "Sit tall and bring the legs inward with controlled pressure.",
  },
  {
    id: "suitcase-carry",
    name: "Suitcase carry",
    category: "strength",
    movementPattern: "carry",
    equipmentTags: ["Dumbbells", "Kettlebell"],
    goalTags: ["strength", "sport_performance", "general_fitness"],
    difficultyTier: "foundation",
    cautionTags: ["back"],
    traitTags: ["loaded", "core", "grip", "unilateral_load"],
    preferenceTags: ["dumbbells", "kettlebell", "carry", "core"],
    sets: 3,
    reps: "20-30 steps each side",
    rest: "75 sec",
    coachingNote: "Walk tall and resist leaning toward the weight.",
  },
  {
    id: "plank",
    name: "Plank",
    category: "core",
    movementPattern: "core",
    equipmentTags: ["Bodyweight"],
    goalTags: [
      "general_fitness",
      "running",
      "sport_performance",
      "consistency",
    ],
    difficultyTier: "intro",
    cautionTags: ["shoulder", "back"],
    traitTags: ["core", "anti_extension"],
    preferenceTags: ["bodyweight", "core"],
    sets: 3,
    reps: "20-40 sec",
    rest: "45 sec",
    coachingNote:
      "Brace gently and keep a straight line from shoulders to ankles.",
  },
  {
    id: "pallof-press",
    name: "Pallof press",
    category: "core",
    movementPattern: "core",
    equipmentTags: ["Cable", "Bands"],
    goalTags: ["general_fitness", "running", "sport_performance"],
    difficultyTier: "foundation",
    cautionTags: [],
    traitTags: ["core", "anti_rotation"],
    preferenceTags: ["cable", "bands", "core"],
    sets: 3,
    reps: "8 each side",
    rest: "45 sec",
    coachingNote: "Press straight out and resist rotating toward the anchor.",
  },
  {
    id: "inverted-row",
    name: "Inverted row",
    category: "strength",
    movementPattern: "pull",
    equipmentTags: ["Bar", "Bodyweight"],
    goalTags: ["general_fitness", "strength", "hypertrophy"],
    difficultyTier: "foundation",
    cautionTags: ["shoulder"],
    traitTags: ["upper_body", "bodyweight"],
    preferenceTags: ["bodyweight", "back", "pull"],
    sets: 3,
    reps: "6-12",
    rest: "90 sec",
    coachingNote: "Keep the body straight and pull the chest toward the bar.",
  },
  {
    id: "wall-sit",
    name: "Wall sit",
    category: "strength",
    movementPattern: "squat",
    equipmentTags: ["Bodyweight"],
    goalTags: ["general_fitness", "running", "consistency"],
    difficultyTier: "intro",
    cautionTags: ["knee"],
    traitTags: ["lower_body", "isometric"],
    preferenceTags: ["bodyweight", "quads", "lower body"],
    sets: 3,
    reps: "20-40 sec",
    rest: "60 sec",
    coachingNote:
      "Hold a comfortable depth and keep the back against the wall.",
  },
  {
    id: "calf-stretch",
    name: "Calf stretch",
    category: "mobility",
    movementPattern: "mobility",
    equipmentTags: ["Bodyweight", "Wall"],
    goalTags: ["recovery", "running", "general_fitness"],
    difficultyTier: "intro",
    cautionTags: ["ankle"],
    traitTags: ["mobility", "low_load"],
    preferenceTags: ["mobility", "calves", "running prep"],
    sets: 2,
    reps: "30 sec each side",
    rest: "15 sec",
    coachingNote: "Ease into the stretch and avoid bouncing.",
  },
  {
    id: "shoulder-wall-slide",
    name: "Shoulder wall slide",
    category: "mobility",
    movementPattern: "mobility",
    equipmentTags: ["Bodyweight", "Wall"],
    goalTags: ["recovery", "general_fitness", "sport_performance"],
    difficultyTier: "intro",
    cautionTags: ["shoulder"],
    traitTags: ["mobility", "upper_body"],
    preferenceTags: ["mobility", "shoulders"],
    sets: 2,
    reps: "8",
    rest: "30 sec",
    coachingNote: "Slide only through a comfortable shoulder range.",
  },
  {
    id: "marching-drill",
    name: "A-march",
    category: "running_prep",
    movementPattern: "run",
    equipmentTags: ["Bodyweight"],
    goalTags: ["running", "sport_performance", "general_fitness"],
    difficultyTier: "intro",
    cautionTags: [],
    traitTags: ["running_support", "low_impact"],
    preferenceTags: ["running prep", "bodyweight"],
    sets: 3,
    reps: "20 sec",
    rest: "40 sec",
    coachingNote: "March tall with relaxed arms and quiet foot contacts.",
  },
  {
    id: "pogo-hop",
    name: "Pogo hop",
    category: "running_prep",
    movementPattern: "power",
    equipmentTags: ["Bodyweight"],
    goalTags: ["running", "sport_performance"],
    difficultyTier: "foundation",
    cautionTags: ["impact", "ankle", "knee"],
    traitTags: ["running_support", "power"],
    preferenceTags: ["running prep", "plyometric"],
    sets: 3,
    reps: "10-15 sec",
    rest: "60 sec",
    coachingNote:
      "Keep hops small and springy; stop if landings get loud or painful.",
  },
  {
    id: "cable-crunch",
    name: "Kneeling cable crunch",
    category: "core",
    movementPattern: "core",
    equipmentTags: ["Cable", "Rope attachment"],
    goalTags: ["hypertrophy", "general_fitness", "strength"],
    difficultyTier: "foundation",
    cautionTags: ["back"],
    traitTags: ["core", "loaded", "trunk_flexion"],
    preferenceTags: ["cable", "core", "abs"],
    sets: 3,
    reps: "10-15",
    rest: "60 sec",
    coachingNote:
      "Curl the ribs toward the pelvis without pulling with the arms or sitting back.",
  },
  {
    id: "machine-abdominal-crunch",
    name: "Machine abdominal crunch",
    category: "core",
    movementPattern: "core",
    equipmentTags: ["Machine"],
    goalTags: ["hypertrophy", "general_fitness", "strength"],
    difficultyTier: "foundation",
    cautionTags: ["back"],
    traitTags: ["core", "machine", "trunk_flexion"],
    preferenceTags: ["machine", "core", "abs"],
    sets: 3,
    reps: "10-15",
    rest: "60 sec",
    coachingNote:
      "Set the machine comfortably and flex through the trunk without jerking the handles.",
  },
  {
    id: "reverse-crunch",
    name: "Reverse crunch",
    category: "core",
    movementPattern: "core",
    equipmentTags: ["Bodyweight"],
    goalTags: [
      "general_fitness",
      "strength",
      "hypertrophy",
      "sport_performance",
    ],
    difficultyTier: "intro",
    cautionTags: ["back"],
    traitTags: ["core", "bodyweight", "trunk_flexion"],
    preferenceTags: ["bodyweight", "core", "home"],
    sets: 3,
    reps: "8-15",
    rest: "45 sec",
    coachingNote:
      "Curl the pelvis toward the ribs without swinging the legs or pushing through the hands.",
  },
  {
    id: "hanging-knee-raise",
    name: "Hanging knee raise",
    category: "core",
    movementPattern: "core",
    equipmentTags: ["Pull-up bar"],
    goalTags: [
      "general_fitness",
      "strength",
      "hypertrophy",
      "sport_performance",
    ],
    difficultyTier: "foundation",
    cautionTags: ["shoulder", "back"],
    traitTags: ["core", "bodyweight", "hanging"],
    preferenceTags: ["bodyweight", "core", "pull-up bar"],
    sets: 3,
    reps: "6-12",
    rest: "75 sec",
    coachingNote:
      "Start from a controlled hang and raise the knees without swinging or shrugging.",
  },
  {
    id: "hanging-straight-leg-raise",
    name: "Hanging straight-leg raise",
    category: "core",
    movementPattern: "core",
    equipmentTags: ["Pull-up bar"],
    goalTags: ["sport_performance", "strength", "general_fitness"],
    difficultyTier: "intermediate",
    cautionTags: ["shoulder", "back"],
    traitTags: ["core", "bodyweight", "hanging"],
    preferenceTags: ["bodyweight", "core", "pull-up bar"],
    sets: 3,
    reps: "5-10",
    rest: "90 sec",
    coachingNote:
      "Keep the legs controlled, avoid swinging, and stop before the low back position changes.",
  },
  {
    id: "captains-chair-knee-raise",
    name: "Captain's-chair knee raise",
    category: "core",
    movementPattern: "core",
    equipmentTags: ["Captain's chair"],
    goalTags: [
      "general_fitness",
      "strength",
      "hypertrophy",
      "sport_performance",
    ],
    difficultyTier: "foundation",
    cautionTags: ["shoulder", "back"],
    traitTags: ["core", "bodyweight", "supported"],
    preferenceTags: ["machine", "core", "abs"],
    sets: 3,
    reps: "8-15",
    rest: "60 sec",
    coachingNote:
      "Press the back into the pad and lift the knees without using momentum.",
  },
  {
    id: "ab-wheel-rollout",
    name: "Ab-wheel rollout",
    category: "core",
    movementPattern: "core",
    equipmentTags: ["Ab wheel"],
    goalTags: ["sport_performance", "strength", "general_fitness"],
    difficultyTier: "intermediate",
    cautionTags: ["back", "shoulder"],
    traitTags: ["core", "anti_extension", "bodyweight"],
    preferenceTags: ["ab wheel", "core", "home"],
    sets: 3,
    reps: "6-12",
    rest: "75 sec",
    coachingNote:
      "Keep the ribs down and roll only as far as you can return without the low back sagging.",
  },
  {
    id: "stability-ball-rollout",
    name: "Stability-ball rollout",
    category: "core",
    movementPattern: "core",
    equipmentTags: ["Stability ball"],
    goalTags: [
      "general_fitness",
      "strength",
      "hypertrophy",
      "sport_performance",
    ],
    difficultyTier: "foundation",
    cautionTags: ["back", "shoulder"],
    traitTags: ["core", "anti_extension", "supported"],
    preferenceTags: ["stability ball", "core", "home"],
    sets: 3,
    reps: "8-12",
    rest: "60 sec",
    coachingNote:
      "Keep a straight line from shoulders to knees and roll the ball forward without losing trunk control.",
  },
  {
    id: "stability-ball-stir-the-pot",
    name: "Stability-ball stir-the-pot",
    category: "core",
    movementPattern: "core",
    equipmentTags: ["Stability ball"],
    goalTags: ["sport_performance", "strength", "general_fitness"],
    difficultyTier: "intermediate",
    cautionTags: ["back", "shoulder"],
    traitTags: ["core", "anti_extension", "dynamic"],
    preferenceTags: ["stability ball", "core", "sport"],
    sets: 3,
    reps: "6 circles each direction",
    rest: "60 sec",
    coachingNote:
      "Hold a firm plank and make small controlled circles without shifting the hips.",
  },
  {
    id: "short-lever-copenhagen-plank",
    name: "Short-lever Copenhagen plank",
    category: "core",
    movementPattern: "core",
    equipmentTags: ["Bench"],
    goalTags: ["sport_performance", "strength", "general_fitness"],
    difficultyTier: "foundation",
    cautionTags: ["knee", "shoulder"],
    traitTags: ["core", "adductor", "isometric", "lateral"],
    preferenceTags: ["bodyweight", "core", "adductors"],
    sets: 3,
    reps: "15-25 sec each side",
    rest: "60 sec",
    coachingNote:
      "Support the top knee on the bench, lift the hips, and hold a straight body line.",
  },
  {
    id: "long-lever-copenhagen-plank",
    name: "Long-lever Copenhagen plank",
    category: "core",
    movementPattern: "core",
    equipmentTags: ["Bench"],
    goalTags: ["sport_performance", "strength", "general_fitness"],
    difficultyTier: "intermediate",
    cautionTags: ["knee", "shoulder"],
    traitTags: ["core", "adductor", "isometric", "lateral"],
    preferenceTags: ["bodyweight", "core", "adductors"],
    sets: 3,
    reps: "10-20 sec each side",
    rest: "75 sec",
    coachingNote:
      "Support the top ankle on the bench and hold the hips level without twisting.",
  },
  {
    id: "side-plank-cable-row",
    name: "Side plank with cable row",
    category: "core",
    movementPattern: "core",
    equipmentTags: ["Cable"],
    goalTags: ["sport_performance", "strength", "general_fitness"],
    difficultyTier: "intermediate",
    cautionTags: ["shoulder", "back"],
    traitTags: ["core", "anti_rotation", "loaded", "unilateral"],
    preferenceTags: ["cable", "core", "row"],
    sets: 3,
    reps: "8-12 each side",
    rest: "75 sec",
    coachingNote:
      "Hold a stable side plank and row the handle without letting the torso rotate.",
  },
  {
    id: "landmine-rotation",
    name: "Landmine rotation",
    category: "core",
    movementPattern: "core",
    equipmentTags: ["Barbell", "Landmine"],
    goalTags: ["sport_performance", "strength", "general_fitness"],
    difficultyTier: "foundation",
    cautionTags: ["back", "shoulder"],
    traitTags: ["core", "rotation", "loaded"],
    preferenceTags: ["barbell", "landmine", "core", "rotation"],
    sets: 3,
    reps: "8-12 each side",
    rest: "75 sec",
    coachingNote:
      "Move the bar in a controlled arc while rotating through the hips and trunk together.",
  },
  {
    id: "double-front-rack-carry",
    name: "Double front-rack carry",
    category: "strength",
    movementPattern: "carry",
    equipmentTags: ["Kettlebell", "Dumbbells"],
    goalTags: ["sport_performance", "strength", "general_fitness"],
    difficultyTier: "foundation",
    cautionTags: ["back"],
    traitTags: ["carry", "loaded", "front_rack", "core"],
    preferenceTags: ["kettlebell", "dumbbells", "carry", "core"],
    sets: 3,
    reps: "20-30 steps",
    rest: "90 sec",
    coachingNote:
      "Keep both weights in a stable front rack, ribs stacked, and steps controlled.",
  },
  {
    id: "single-arm-front-rack-carry",
    name: "Single-arm front-rack carry",
    category: "strength",
    movementPattern: "carry",
    equipmentTags: ["Kettlebell", "Dumbbells"],
    goalTags: ["sport_performance", "strength", "general_fitness"],
    difficultyTier: "foundation",
    cautionTags: ["back"],
    traitTags: ["carry", "loaded", "unilateral", "anti_lateral_flexion"],
    preferenceTags: ["kettlebell", "dumbbells", "carry", "core"],
    sets: 3,
    reps: "20-30 steps each side",
    rest: "90 sec",
    coachingNote:
      "Hold one weight in the front rack and walk without leaning or rotating.",
  },
  {
    id: "bear-hug-sandbag-carry",
    name: "Bear-hug sandbag carry",
    category: "strength",
    movementPattern: "carry",
    equipmentTags: ["Sandbag"],
    goalTags: [
      "general_fitness",
      "strength",
      "hypertrophy",
      "sport_performance",
    ],
    difficultyTier: "foundation",
    cautionTags: ["back"],
    traitTags: ["carry", "loaded", "front_loaded"],
    preferenceTags: ["sandbag", "carry", "general fitness"],
    sets: 3,
    reps: "20-40 m",
    rest: "90 sec",
    coachingNote:
      "Hug the bag close, keep the chest tall, and take steady controlled steps.",
  },
  {
    id: "zercher-carry",
    name: "Zercher carry",
    category: "strength",
    movementPattern: "carry",
    equipmentTags: ["Barbell"],
    goalTags: ["sport_performance", "strength", "general_fitness"],
    difficultyTier: "intermediate",
    cautionTags: ["back"],
    traitTags: ["carry", "loaded", "front_loaded"],
    preferenceTags: ["barbell", "carry", "core", "strength"],
    sets: 3,
    reps: "15-25 m",
    rest: "2 min",
    coachingNote:
      "Hold the bar securely in the elbow creases and walk tall without losing the brace.",
  },
  {
    id: "trap-bar-carry",
    name: "Trap-bar carry",
    category: "strength",
    movementPattern: "carry",
    equipmentTags: ["Trap bar"],
    goalTags: ["sport_performance", "strength", "general_fitness"],
    difficultyTier: "foundation",
    cautionTags: ["back"],
    traitTags: ["carry", "loaded", "grip"],
    preferenceTags: ["trap bar", "carry", "grip", "strength"],
    sets: 3,
    reps: "20-30 m",
    rest: "90 sec",
    coachingNote:
      "Stand tall inside the trap bar and walk with short controlled steps.",
  },
  {
    id: "single-arm-waiter-carry",
    name: "Single-arm waiter carry",
    category: "strength",
    movementPattern: "carry",
    equipmentTags: ["Kettlebell", "Dumbbells"],
    goalTags: ["sport_performance", "strength", "general_fitness"],
    difficultyTier: "intermediate",
    cautionTags: ["shoulder", "overhead", "back"],
    traitTags: ["carry", "loaded", "unilateral", "overhead"],
    preferenceTags: ["kettlebell", "dumbbells", "carry", "shoulder stability"],
    sets: 3,
    reps: "15-25 m each side",
    rest: "90 sec",
    coachingNote:
      "Keep the weight stacked overhead, ribs down, and torso upright while walking.",
  },
  {
    id: "standing-cable-hip-adduction",
    name: "Standing cable hip adduction",
    category: "strength",
    movementPattern: "lateral",
    equipmentTags: ["Cable", "Ankle strap"],
    goalTags: [
      "general_fitness",
      "strength",
      "hypertrophy",
      "sport_performance",
    ],
    difficultyTier: "foundation",
    cautionTags: ["knee"],
    traitTags: ["unilateral", "loaded", "adductor"],
    preferenceTags: ["cable", "adductors", "single leg"],
    sets: 3,
    reps: "10-15 each side",
    rest: "60 sec",
    coachingNote:
      "Hold support and draw the working leg across the body without leaning.",
  },
  {
    id: "side-lying-hip-adduction",
    name: "Side-lying hip adduction",
    category: "recovery",
    movementPattern: "lateral",
    equipmentTags: ["Bodyweight"],
    goalTags: ["recovery", "consistency", "general_fitness"],
    difficultyTier: "intro",
    cautionTags: ["knee"],
    traitTags: ["unilateral", "bodyweight", "adductor"],
    preferenceTags: ["bodyweight", "adductors", "home"],
    sets: 3,
    reps: "12-20 each side",
    rest: "45 sec",
    coachingNote:
      "Keep the top leg supported and lift the lower leg without rolling the pelvis.",
  },
  {
    id: "slider-adductor-slide-out",
    name: "Slider adductor slide-out",
    category: "strength",
    movementPattern: "lateral",
    equipmentTags: ["Sliders"],
    goalTags: ["sport_performance", "strength", "general_fitness"],
    difficultyTier: "intermediate",
    cautionTags: ["knee"],
    traitTags: ["unilateral", "bodyweight", "adductor", "eccentric"],
    preferenceTags: ["sliders", "adductors", "sport"],
    sets: 3,
    reps: "6-10 each side",
    rest: "75 sec",
    coachingNote:
      "Slide one foot outward slowly while keeping the stance leg and pelvis controlled.",
  },
  {
    id: "single-arm-kettlebell-clean",
    name: "Single-arm kettlebell clean",
    category: "athletic",
    movementPattern: "power",
    equipmentTags: ["Kettlebell"],
    goalTags: ["sport_performance", "strength", "general_fitness"],
    difficultyTier: "foundation",
    cautionTags: ["shoulder", "back"],
    traitTags: ["power", "loaded", "unilateral", "kettlebell_skill"],
    preferenceTags: ["kettlebell", "power", "single arm"],
    sets: 4,
    reps: "5-8 each side",
    rest: "90 sec",
    coachingNote:
      "Drive the bell with the hips and guide it softly into the rack without letting it crash.",
  },
  {
    id: "double-kettlebell-clean",
    name: "Double-kettlebell clean",
    category: "athletic",
    movementPattern: "power",
    equipmentTags: ["Kettlebell"],
    goalTags: ["sport_performance", "strength", "general_fitness"],
    difficultyTier: "intermediate",
    cautionTags: ["shoulder", "back"],
    traitTags: ["power", "loaded", "bilateral", "kettlebell_skill"],
    preferenceTags: ["kettlebell", "power", "conditioning"],
    sets: 4,
    reps: "4-6",
    rest: "2 min",
    coachingNote:
      "Use a compact hip drive and guide both bells into a stable front rack.",
  },
  {
    id: "single-arm-kettlebell-snatch",
    name: "Single-arm kettlebell snatch",
    category: "athletic",
    movementPattern: "power",
    equipmentTags: ["Kettlebell"],
    goalTags: ["sport_performance", "strength", "general_fitness"],
    difficultyTier: "intermediate",
    cautionTags: ["shoulder", "overhead", "back"],
    traitTags: ["power", "loaded", "unilateral", "overhead"],
    preferenceTags: ["kettlebell", "power", "single arm", "overhead"],
    sets: 4,
    reps: "4-6 each side",
    rest: "2 min",
    coachingNote:
      "Drive the bell from the hips and punch through smoothly so it settles overhead without impact.",
  },
  {
    id: "turkish-get-up",
    name: "Turkish get-up",
    category: "athletic",
    movementPattern: "core",
    equipmentTags: ["Kettlebell", "Dumbbells"],
    goalTags: ["sport_performance", "strength", "general_fitness"],
    difficultyTier: "intermediate",
    cautionTags: ["shoulder", "overhead", "back", "knee"],
    traitTags: ["full_body", "loaded", "unilateral", "floor_transfer"],
    preferenceTags: ["kettlebell", "core", "shoulder stability"],
    sets: 3,
    reps: "1-3 each side",
    rest: "2 min",
    coachingNote:
      "Move through each position slowly, keep the weight stacked, and maintain visual control of the load.",
  },
  {
    id: "barbell-power-clean",
    name: "Barbell power clean",
    category: "athletic",
    movementPattern: "power",
    equipmentTags: ["Barbell"],
    goalTags: ["sport_performance", "strength", "general_fitness"],
    difficultyTier: "intermediate",
    cautionTags: ["back", "shoulder", "loaded_spine"],
    traitTags: ["power", "higher_load", "olympic_derivative"],
    preferenceTags: ["barbell", "power", "sport"],
    sets: 5,
    reps: "2-4",
    rest: "2-3 min",
    coachingNote:
      "Keep the bar close, extend through the hips, and receive it in a stable partial squat.",
  },
  {
    id: "hang-power-clean",
    name: "Hang power clean",
    category: "athletic",
    movementPattern: "power",
    equipmentTags: ["Barbell"],
    goalTags: ["sport_performance", "strength", "general_fitness"],
    difficultyTier: "intermediate",
    cautionTags: ["back", "shoulder", "loaded_spine"],
    traitTags: ["power", "higher_load", "olympic_derivative"],
    preferenceTags: ["barbell", "power", "sport"],
    sets: 5,
    reps: "2-4",
    rest: "2-3 min",
    coachingNote:
      "Start from a controlled hang, drive vertically, and catch the bar with balanced feet.",
  },
  {
    id: "barbell-clean-pull",
    name: "Barbell clean pull",
    category: "athletic",
    movementPattern: "power",
    equipmentTags: ["Barbell"],
    goalTags: ["sport_performance", "strength", "general_fitness"],
    difficultyTier: "intermediate",
    cautionTags: ["back", "loaded_spine"],
    traitTags: ["power", "higher_load", "olympic_derivative"],
    preferenceTags: ["barbell", "power", "posterior chain"],
    sets: 4,
    reps: "3-5",
    rest: "2-3 min",
    coachingNote:
      "Push through the floor, keep the bar close, and finish tall without pulling early with the arms.",
  },
  {
    id: "barbell-high-pull",
    name: "Barbell high pull",
    category: "athletic",
    movementPattern: "power",
    equipmentTags: ["Barbell"],
    goalTags: ["sport_performance", "strength", "general_fitness"],
    difficultyTier: "intermediate",
    cautionTags: ["back", "shoulder", "loaded_spine"],
    traitTags: ["power", "higher_load", "olympic_derivative"],
    preferenceTags: ["barbell", "power", "upper body"],
    sets: 4,
    reps: "3-5",
    rest: "2 min",
    coachingNote:
      "Extend through the hips and guide the elbows high while keeping the bar close.",
  },
  {
    id: "dumbbell-hang-power-clean",
    name: "Dumbbell hang power clean",
    category: "athletic",
    movementPattern: "power",
    equipmentTags: ["Dumbbells"],
    goalTags: ["sport_performance", "strength", "general_fitness"],
    difficultyTier: "foundation",
    cautionTags: ["back", "shoulder"],
    traitTags: ["power", "loaded", "bilateral"],
    preferenceTags: ["dumbbells", "power", "sport"],
    sets: 4,
    reps: "4-6",
    rest: "90 sec",
    coachingNote:
      "Start from a shallow hinge, drive through the hips, and receive the dumbbells at the shoulders.",
  },
  {
    id: "jump-rope",
    name: "Jump rope",
    category: "cardio",
    movementPattern: "power",
    equipmentTags: ["Jump rope"],
    goalTags: ["general_fitness", "consistency", "sport_performance"],
    difficultyTier: "foundation",
    cautionTags: ["ankle", "knee", "impact"],
    traitTags: ["cardio", "elastic", "low_setup"],
    preferenceTags: ["jump rope", "cardio", "home"],
    sets: 5,
    reps: "60 sec",
    rest: "30 sec",
    coachingNote:
      "Use small quiet jumps, keep the elbows close, and turn the rope from the wrists.",
  },
  {
    id: "ski-ergometer",
    name: "Ski ergometer",
    category: "cardio",
    movementPattern: "run",
    equipmentTags: ["Ski ergometer"],
    goalTags: ["general_fitness", "consistency", "sport_performance"],
    difficultyTier: "foundation",
    cautionTags: ["shoulder", "back"],
    traitTags: ["cardio", "machine", "full_body"],
    preferenceTags: ["ski erg", "cardio", "conditioning"],
    sets: 1,
    reps: "10-20 min",
    rest: "As needed",
    coachingNote:
      "Use a smooth hip hinge and arm pull while keeping a sustainable rhythm.",
  },
  {
    id: "battle-rope-alternating-waves",
    name: "Battle-rope alternating waves",
    category: "cardio",
    movementPattern: "power",
    equipmentTags: ["Battle ropes"],
    goalTags: ["general_fitness", "sport_performance"],
    difficultyTier: "foundation",
    cautionTags: ["shoulder", "back"],
    traitTags: ["cardio", "upper_body", "interval"],
    preferenceTags: ["battle ropes", "conditioning", "upper body"],
    sets: 6,
    reps: "20-30 sec",
    rest: "60 sec",
    coachingNote:
      "Stay in a stable stance and create consistent alternating waves without shrugging.",
  },
  {
    id: "battle-rope-slams",
    name: "Battle-rope slams",
    category: "cardio",
    movementPattern: "power",
    equipmentTags: ["Battle ropes"],
    goalTags: ["general_fitness", "sport_performance"],
    difficultyTier: "foundation",
    cautionTags: ["shoulder", "overhead", "back"],
    traitTags: ["cardio", "full_body", "interval"],
    preferenceTags: ["battle ropes", "conditioning", "power"],
    sets: 6,
    reps: "15-20 sec",
    rest: "60 sec",
    coachingNote:
      "Raise both ropes under control and drive them down using the hips and trunk.",
  },
  {
    id: "hand-over-hand-sled-pull",
    name: "Hand-over-hand sled pull",
    category: "athletic",
    movementPattern: "pull",
    equipmentTags: ["Sled", "Rope"],
    goalTags: ["sport_performance", "strength", "general_fitness"],
    difficultyTier: "foundation",
    cautionTags: ["back", "shoulder"],
    traitTags: ["conditioning", "loaded", "upper_body"],
    preferenceTags: ["sled", "rope", "conditioning", "pull"],
    sets: 4,
    reps: "15-25 m",
    rest: "90 sec",
    coachingNote:
      "Brace in a stable stance and pull the rope hand over hand without rounding the back.",
  },
] satisfies Array<Omit<ExerciseCatalogItem, keyof ExerciseTrackingMetadata>>;

const catalogMetadataOverrides: Record<string, ExerciseTrackingMetadata> = {
  "cable-crunch": {
    trackingType: "weight_reps",
    unilateralMode: "bilateral",
    loadUnit: "lb",
    supportedLoadUnits: ["lb", "kg"],
    distanceUnit: null,
    supportedDistanceUnits: [],
    primaryValueLabel: "Load",
    secondaryValueLabel: "Reps",
  },
  "machine-abdominal-crunch": {
    trackingType: "weight_reps",
    unilateralMode: "bilateral",
    loadUnit: "lb",
    supportedLoadUnits: ["lb", "kg"],
    distanceUnit: null,
    supportedDistanceUnits: [],
    primaryValueLabel: "Load",
    secondaryValueLabel: "Reps",
  },
  "reverse-crunch": {
    trackingType: "reps_only",
    unilateralMode: "bilateral",
    loadUnit: null,
    supportedLoadUnits: [],
    distanceUnit: null,
    supportedDistanceUnits: [],
    primaryValueLabel: "Reps",
    secondaryValueLabel: null,
  },
  "hanging-knee-raise": {
    trackingType: "reps_only",
    unilateralMode: "bilateral",
    loadUnit: null,
    supportedLoadUnits: [],
    distanceUnit: null,
    supportedDistanceUnits: [],
    primaryValueLabel: "Reps",
    secondaryValueLabel: null,
  },
  "hanging-straight-leg-raise": {
    trackingType: "reps_only",
    unilateralMode: "bilateral",
    loadUnit: null,
    supportedLoadUnits: [],
    distanceUnit: null,
    supportedDistanceUnits: [],
    primaryValueLabel: "Reps",
    secondaryValueLabel: null,
  },
  "captains-chair-knee-raise": {
    trackingType: "reps_only",
    unilateralMode: "bilateral",
    loadUnit: null,
    supportedLoadUnits: [],
    distanceUnit: null,
    supportedDistanceUnits: [],
    primaryValueLabel: "Reps",
    secondaryValueLabel: null,
  },
  "ab-wheel-rollout": {
    trackingType: "reps_only",
    unilateralMode: "bilateral",
    loadUnit: null,
    supportedLoadUnits: [],
    distanceUnit: null,
    supportedDistanceUnits: [],
    primaryValueLabel: "Reps",
    secondaryValueLabel: null,
  },
  "stability-ball-rollout": {
    trackingType: "reps_only",
    unilateralMode: "bilateral",
    loadUnit: null,
    supportedLoadUnits: [],
    distanceUnit: null,
    supportedDistanceUnits: [],
    primaryValueLabel: "Reps",
    secondaryValueLabel: null,
  },
  "stability-ball-stir-the-pot": {
    trackingType: "reps_only",
    unilateralMode: "bilateral",
    loadUnit: null,
    supportedLoadUnits: [],
    distanceUnit: null,
    supportedDistanceUnits: [],
    primaryValueLabel: "Reps",
    secondaryValueLabel: null,
  },
  "short-lever-copenhagen-plank": {
    trackingType: "duration",
    unilateralMode: "same_each_side",
    loadUnit: null,
    supportedLoadUnits: [],
    distanceUnit: null,
    supportedDistanceUnits: [],
    primaryValueLabel: "Duration",
    secondaryValueLabel: null,
  },
  "long-lever-copenhagen-plank": {
    trackingType: "duration",
    unilateralMode: "same_each_side",
    loadUnit: null,
    supportedLoadUnits: [],
    distanceUnit: null,
    supportedDistanceUnits: [],
    primaryValueLabel: "Duration",
    secondaryValueLabel: null,
  },
  "side-plank-cable-row": {
    trackingType: "weight_reps",
    unilateralMode: "same_each_side",
    loadUnit: "lb",
    supportedLoadUnits: ["lb", "kg"],
    distanceUnit: null,
    supportedDistanceUnits: [],
    primaryValueLabel: "Load",
    secondaryValueLabel: "Reps",
  },
  "landmine-rotation": {
    trackingType: "weight_reps",
    unilateralMode: "same_each_side",
    loadUnit: "lb",
    supportedLoadUnits: ["lb", "kg"],
    distanceUnit: null,
    supportedDistanceUnits: [],
    primaryValueLabel: "Load",
    secondaryValueLabel: "Reps",
  },
  "double-front-rack-carry": {
    trackingType: "weight_reps",
    unilateralMode: "bilateral",
    loadUnit: "lb",
    supportedLoadUnits: ["lb", "kg"],
    distanceUnit: null,
    supportedDistanceUnits: [],
    primaryValueLabel: "Load",
    secondaryValueLabel: "Steps",
  },
  "single-arm-front-rack-carry": {
    trackingType: "weight_reps",
    unilateralMode: "same_each_side",
    loadUnit: "lb",
    supportedLoadUnits: ["lb", "kg"],
    distanceUnit: null,
    supportedDistanceUnits: [],
    primaryValueLabel: "Load",
    secondaryValueLabel: "Steps",
  },
  "bear-hug-sandbag-carry": {
    trackingType: "weight_reps",
    unilateralMode: "bilateral",
    loadUnit: "lb",
    supportedLoadUnits: ["lb", "kg"],
    distanceUnit: null,
    supportedDistanceUnits: [],
    primaryValueLabel: "Load",
    secondaryValueLabel: "Distance",
  },
  "zercher-carry": {
    trackingType: "weight_reps",
    unilateralMode: "bilateral",
    loadUnit: "lb",
    supportedLoadUnits: ["lb", "kg"],
    distanceUnit: null,
    supportedDistanceUnits: [],
    primaryValueLabel: "Load",
    secondaryValueLabel: "Distance",
  },
  "trap-bar-carry": {
    trackingType: "weight_reps",
    unilateralMode: "bilateral",
    loadUnit: "lb",
    supportedLoadUnits: ["lb", "kg"],
    distanceUnit: null,
    supportedDistanceUnits: [],
    primaryValueLabel: "Load",
    secondaryValueLabel: "Distance",
  },
  "single-arm-waiter-carry": {
    trackingType: "weight_reps",
    unilateralMode: "same_each_side",
    loadUnit: "lb",
    supportedLoadUnits: ["lb", "kg"],
    distanceUnit: null,
    supportedDistanceUnits: [],
    primaryValueLabel: "Load",
    secondaryValueLabel: "Distance",
  },
  "standing-cable-hip-adduction": {
    trackingType: "weight_reps",
    unilateralMode: "same_each_side",
    loadUnit: "lb",
    supportedLoadUnits: ["lb", "kg"],
    distanceUnit: null,
    supportedDistanceUnits: [],
    primaryValueLabel: "Load",
    secondaryValueLabel: "Reps",
  },
  "side-lying-hip-adduction": {
    trackingType: "reps_only",
    unilateralMode: "same_each_side",
    loadUnit: null,
    supportedLoadUnits: [],
    distanceUnit: null,
    supportedDistanceUnits: [],
    primaryValueLabel: "Reps",
    secondaryValueLabel: null,
  },
  "slider-adductor-slide-out": {
    trackingType: "reps_only",
    unilateralMode: "same_each_side",
    loadUnit: null,
    supportedLoadUnits: [],
    distanceUnit: null,
    supportedDistanceUnits: [],
    primaryValueLabel: "Reps",
    secondaryValueLabel: null,
  },
  "single-arm-kettlebell-clean": {
    trackingType: "weight_reps",
    unilateralMode: "same_each_side",
    loadUnit: "lb",
    supportedLoadUnits: ["lb", "kg"],
    distanceUnit: null,
    supportedDistanceUnits: [],
    primaryValueLabel: "Load",
    secondaryValueLabel: "Reps",
  },
  "double-kettlebell-clean": {
    trackingType: "weight_reps",
    unilateralMode: "bilateral",
    loadUnit: "lb",
    supportedLoadUnits: ["lb", "kg"],
    distanceUnit: null,
    supportedDistanceUnits: [],
    primaryValueLabel: "Load",
    secondaryValueLabel: "Reps",
  },
  "single-arm-kettlebell-snatch": {
    trackingType: "weight_reps",
    unilateralMode: "same_each_side",
    loadUnit: "lb",
    supportedLoadUnits: ["lb", "kg"],
    distanceUnit: null,
    supportedDistanceUnits: [],
    primaryValueLabel: "Load",
    secondaryValueLabel: "Reps",
  },
  "turkish-get-up": {
    trackingType: "weight_reps",
    unilateralMode: "same_each_side",
    loadUnit: "lb",
    supportedLoadUnits: ["lb", "kg"],
    distanceUnit: null,
    supportedDistanceUnits: [],
    primaryValueLabel: "Load",
    secondaryValueLabel: "Reps",
  },
  "barbell-power-clean": {
    trackingType: "weight_reps",
    unilateralMode: "bilateral",
    loadUnit: "lb",
    supportedLoadUnits: ["lb", "kg"],
    distanceUnit: null,
    supportedDistanceUnits: [],
    primaryValueLabel: "Load",
    secondaryValueLabel: "Reps",
  },
  "hang-power-clean": {
    trackingType: "weight_reps",
    unilateralMode: "bilateral",
    loadUnit: "lb",
    supportedLoadUnits: ["lb", "kg"],
    distanceUnit: null,
    supportedDistanceUnits: [],
    primaryValueLabel: "Load",
    secondaryValueLabel: "Reps",
  },
  "barbell-clean-pull": {
    trackingType: "weight_reps",
    unilateralMode: "bilateral",
    loadUnit: "lb",
    supportedLoadUnits: ["lb", "kg"],
    distanceUnit: null,
    supportedDistanceUnits: [],
    primaryValueLabel: "Load",
    secondaryValueLabel: "Reps",
  },
  "barbell-high-pull": {
    trackingType: "weight_reps",
    unilateralMode: "bilateral",
    loadUnit: "lb",
    supportedLoadUnits: ["lb", "kg"],
    distanceUnit: null,
    supportedDistanceUnits: [],
    primaryValueLabel: "Load",
    secondaryValueLabel: "Reps",
  },
  "dumbbell-hang-power-clean": {
    trackingType: "weight_reps",
    unilateralMode: "bilateral",
    loadUnit: "lb",
    supportedLoadUnits: ["lb", "kg"],
    distanceUnit: null,
    supportedDistanceUnits: [],
    primaryValueLabel: "Load",
    secondaryValueLabel: "Reps",
  },
  "jump-rope": {
    trackingType: "duration",
    unilateralMode: "bilateral",
    loadUnit: null,
    supportedLoadUnits: [],
    distanceUnit: null,
    supportedDistanceUnits: [],
    primaryValueLabel: "Duration",
    secondaryValueLabel: null,
  },
  "ski-ergometer": {
    trackingType: "duration",
    unilateralMode: "bilateral",
    loadUnit: null,
    supportedLoadUnits: [],
    distanceUnit: null,
    supportedDistanceUnits: [],
    primaryValueLabel: "Duration",
    secondaryValueLabel: null,
  },
  "battle-rope-alternating-waves": {
    trackingType: "duration",
    unilateralMode: "bilateral",
    loadUnit: null,
    supportedLoadUnits: [],
    distanceUnit: null,
    supportedDistanceUnits: [],
    primaryValueLabel: "Duration",
    secondaryValueLabel: null,
  },
  "battle-rope-slams": {
    trackingType: "duration",
    unilateralMode: "bilateral",
    loadUnit: null,
    supportedLoadUnits: [],
    distanceUnit: null,
    supportedDistanceUnits: [],
    primaryValueLabel: "Duration",
    secondaryValueLabel: null,
  },
  "hand-over-hand-sled-pull": {
    trackingType: "weight_reps",
    unilateralMode: "bilateral",
    loadUnit: "lb",
    supportedLoadUnits: ["lb", "kg"],
    distanceUnit: null,
    supportedDistanceUnits: [],
    primaryValueLabel: "Load",
    secondaryValueLabel: "Distance",
  },
  "goblet-squat": weightRepsMetadata(),
  "barbell-back-squat": weightRepsMetadata(),
  "romanian-deadlift": weightRepsMetadata(),
  "reverse-lunge": repsMetadata("same_each_side"),
  "step-up": repsMetadata("same_each_side"),
  "walking-lunge": repsMetadata("same_each_side"),
  "dumbbell-floor-press": weightRepsMetadata(),
  "dumbbell-shoulder-press": weightRepsMetadata(),
  "dumbbell-row": weightRepsMetadata("same_each_side"),
  "farmer-carry": weightRepsMetadata("bilateral", {
    secondaryValueLabel: "Steps",
  }),
  "dead-bug": repsMetadata("same_each_side"),
  "side-plank": durationMetadata("same_each_side"),
  "dumbbell-lateral-raise": weightRepsMetadata(),
  "dumbbell-curl": weightRepsMetadata(),
  "half-kneeling-hip-flexor-stretch": durationMetadata("same_each_side"),
  "thoracic-rotation": repsMetadata("same_each_side"),
  "ankle-rock": repsMetadata("same_each_side"),
  "brisk-walk": durationMetadata(),
  "low-impact-cardio-march": durationMetadata(),
  "run-walk-intervals": durationMetadata(),
  "easy-run": distanceDurationMetadata,
  "lateral-lunge": weightRepsMetadata("same_each_side"),
  "skater-hop": repsMetadata("same_each_side"),
  "front-squat": weightRepsMetadata(),
  "dumbbell-squat": weightRepsMetadata(),
  "leg-press": weightRepsMetadata(),
  "leg-extension": weightRepsMetadata(),
  "split-squat": weightRepsMetadata("same_each_side"),
  "bulgarian-split-squat": weightRepsMetadata("same_each_side"),
  "forward-lunge": weightRepsMetadata("same_each_side"),
  "conventional-deadlift": weightRepsMetadata(),
  "trap-bar-deadlift": weightRepsMetadata(),
  "dumbbell-romanian-deadlift": weightRepsMetadata(),
  "hip-thrust": weightRepsMetadata(),
  "back-extension": repsMetadata(),
  "seated-leg-curl": weightRepsMetadata(),
  "barbell-bench-press": weightRepsMetadata(),
  "dumbbell-bench-press": weightRepsMetadata(),
  "incline-dumbbell-press": weightRepsMetadata(),
  "incline-barbell-bench-press": weightRepsMetadata(),
  "close-grip-barbell-bench-press": weightRepsMetadata(),
  "machine-chest-press": weightRepsMetadata(),
  "barbell-overhead-press": weightRepsMetadata(),
  "triceps-pushdown": weightRepsMetadata(),
  "seated-cable-row": weightRepsMetadata(),
  "chest-supported-row": weightRepsMetadata(),
  "barbell-row": weightRepsMetadata(),
  "t-bar-row": weightRepsMetadata(),
  "lat-pulldown": weightRepsMetadata(),
  "pull-up": repsMetadata(),
  "chin-up": repsMetadata(),
  "assisted-pull-up": repsMetadata(),
  "face-pull": weightRepsMetadata(),
  "reverse-fly": weightRepsMetadata(),
  "barbell-shrug": weightRepsMetadata(),
  "ez-bar-curl": weightRepsMetadata(),
  "chest-dip": repsMetadata(),
  "hack-squat": weightRepsMetadata(),
  "lying-leg-curl": weightRepsMetadata(),
  "seated-calf-raise": weightRepsMetadata(),
  "cable-fly": weightRepsMetadata(),
  "pec-deck": weightRepsMetadata(),
  "cable-lateral-raise": weightRepsMetadata(),
  "hammer-curl": weightRepsMetadata(),
  "cable-overhead-triceps-extension": weightRepsMetadata(),
  "hip-abduction-machine": weightRepsMetadata(),
  "hip-adduction-machine": weightRepsMetadata(),
  "suitcase-carry": weightRepsMetadata("same_each_side", {
    secondaryValueLabel: "Steps",
  }),
  plank: durationMetadata(),
  "pallof-press": repsMetadata("same_each_side"),
  "inverted-row": repsMetadata(),
  "wall-sit": durationMetadata(),
  "calf-stretch": durationMetadata("same_each_side"),
  "shoulder-wall-slide": repsMetadata(),
  "stride-drills": durationMetadata(),
  "lateral-shuffle": durationMetadata(),
  "marching-drill": durationMetadata(),
  "pogo-hop": durationMetadata(),
};

export const exerciseCatalog: ExerciseCatalogItem[] = exerciseCatalogBase.map(
  (item) => ({
    ...repsMetadata(),
    ...(catalogMetadataOverrides[item.id] ?? {}),
    ...item,
  }),
);

export function getExerciseTrackingMetadataBySourceId(
  sourceExerciseId?: string | null,
): ExerciseTrackingMetadata {
  if (!sourceExerciseId) return completionMetadata;
  const item = exerciseCatalog.find(
    (exercise) => exercise.id === sourceExerciseId,
  );
  if (!item) return completionMetadata;
  return {
    trackingType: item.trackingType,
    unilateralMode: item.unilateralMode,
    loadUnit: item.loadUnit,
    supportedLoadUnits: item.supportedLoadUnits,
    distanceUnit: item.distanceUnit,
    supportedDistanceUnits: item.supportedDistanceUnits,
    primaryValueLabel: item.primaryValueLabel,
    secondaryValueLabel: item.secondaryValueLabel,
  };
}

export function getCatalogExercise(id: string) {
  return exerciseCatalog.find((exercise) => exercise.id === id);
}

export function toPlanExercise(
  item: ExerciseCatalogItem,
): StructuredExerciseInput {
  return {
    sourceExerciseId: item.id,
    name: item.name,
    sets: item.sets,
    reps: item.reps,
    rest: item.rest,
    coachingNote: item.coachingNote,
    videoUrl: item.videoUrl,
  };
}
