-- Issue #98, Slice 1 read-only hosted verification. Every affected_rows value must be 0.
with expected(id, display_name, normalized_lookup_key, owner_scope, equipment_tags, movement_pattern, qualifier_text, metadata) as (values
  ('cable-crunch','Kneeling cable crunch','kneeling cable crunch','system',array['Cable','Rope attachment']::text[],'core','Cable/Rope attachment · bilateral · core','{"category":"core","difficultyTier":"foundation","cautionTags":["back"],"traitTags":["core","loaded","trunk_flexion"],"preferenceTags":["cable","core","abs"]}'::jsonb),
  ('machine-abdominal-crunch','Machine abdominal crunch','machine abdominal crunch','system',array['Machine']::text[],'core','Machine · bilateral · core','{"category":"core","difficultyTier":"foundation","cautionTags":["back"],"traitTags":["core","machine","trunk_flexion"],"preferenceTags":["machine","core","abs"]}'::jsonb),
  ('reverse-crunch','Reverse crunch','reverse crunch','system',array['Bodyweight']::text[],'core','Bodyweight · bilateral · core','{"category":"core","difficultyTier":"intro","cautionTags":["back"],"traitTags":["core","bodyweight","trunk_flexion"],"preferenceTags":["bodyweight","core","home"]}'::jsonb),
  ('hanging-knee-raise','Hanging knee raise','hanging knee raise','system',array['Pull-up bar']::text[],'core','Pull-up bar · bilateral · core','{"category":"core","difficultyTier":"foundation","cautionTags":["shoulder","back"],"traitTags":["core","bodyweight","hanging"],"preferenceTags":["bodyweight","core","pull-up bar"]}'::jsonb),
  ('hanging-straight-leg-raise','Hanging straight-leg raise','hanging straight leg raise','system',array['Pull-up bar']::text[],'core','Pull-up bar · bilateral · core','{"category":"core","difficultyTier":"intermediate","cautionTags":["shoulder","back"],"traitTags":["core","bodyweight","hanging"],"preferenceTags":["bodyweight","core","pull-up bar"]}'::jsonb),
  ('captains-chair-knee-raise','Captain''s-chair knee raise','captains chair knee raise','system',array['Captain''s chair']::text[],'core','Captain''s chair · bilateral · core','{"category":"core","difficultyTier":"foundation","cautionTags":["shoulder","back"],"traitTags":["core","bodyweight","supported"],"preferenceTags":["machine","core","abs"]}'::jsonb),
  ('ab-wheel-rollout','Ab-wheel rollout','ab wheel rollout','system',array['Ab wheel']::text[],'core','Ab wheel · bilateral · core','{"category":"core","difficultyTier":"intermediate","cautionTags":["back","shoulder"],"traitTags":["core","anti_extension","bodyweight"],"preferenceTags":["ab wheel","core","home"]}'::jsonb),
  ('stability-ball-rollout','Stability-ball rollout','stability ball rollout','system',array['Stability ball']::text[],'core','Stability ball · bilateral · core','{"category":"core","difficultyTier":"foundation","cautionTags":["back","shoulder"],"traitTags":["core","anti_extension","supported"],"preferenceTags":["stability ball","core","home"]}'::jsonb),
  ('stability-ball-stir-the-pot','Stability-ball stir-the-pot','stability ball stir the pot','system',array['Stability ball']::text[],'core','Stability ball · bilateral · core','{"category":"core","difficultyTier":"intermediate","cautionTags":["back","shoulder"],"traitTags":["core","anti_extension","dynamic"],"preferenceTags":["stability ball","core","sport"]}'::jsonb),
  ('short-lever-copenhagen-plank','Short-lever Copenhagen plank','short lever copenhagen plank','system',array['Bench']::text[],'core','Bench · same each side · core','{"category":"core","difficultyTier":"foundation","cautionTags":["knee","shoulder"],"traitTags":["core","adductor","isometric","lateral"],"preferenceTags":["bodyweight","core","adductors"]}'::jsonb),
  ('long-lever-copenhagen-plank','Long-lever Copenhagen plank','long lever copenhagen plank','system',array['Bench']::text[],'core','Bench · same each side · core','{"category":"core","difficultyTier":"intermediate","cautionTags":["knee","shoulder"],"traitTags":["core","adductor","isometric","lateral"],"preferenceTags":["bodyweight","core","adductors"]}'::jsonb),
  ('side-plank-cable-row','Side plank with cable row','side plank with cable row','system',array['Cable']::text[],'core','Cable · same each side · core','{"category":"core","difficultyTier":"intermediate","cautionTags":["shoulder","back"],"traitTags":["core","anti_rotation","loaded","unilateral"],"preferenceTags":["cable","core","row"]}'::jsonb),
  ('landmine-rotation','Landmine rotation','landmine rotation','system',array['Barbell','Landmine']::text[],'core','Barbell/Landmine · same each side · core','{"category":"core","difficultyTier":"foundation","cautionTags":["back","shoulder"],"traitTags":["core","rotation","loaded"],"preferenceTags":["barbell","landmine","core","rotation"]}'::jsonb),
  ('double-front-rack-carry','Double front-rack carry','double front rack carry','system',array['Kettlebell','Dumbbells']::text[],'carry','Kettlebell/Dumbbells · bilateral · carry','{"category":"strength","difficultyTier":"foundation","cautionTags":["back"],"traitTags":["carry","loaded","front_rack","core"],"preferenceTags":["kettlebell","dumbbells","carry","core"]}'::jsonb),
  ('single-arm-front-rack-carry','Single-arm front-rack carry','single arm front rack carry','system',array['Kettlebell','Dumbbells']::text[],'carry','Kettlebell/Dumbbells · same each side · carry','{"category":"strength","difficultyTier":"foundation","cautionTags":["back"],"traitTags":["carry","loaded","unilateral","anti_lateral_flexion"],"preferenceTags":["kettlebell","dumbbells","carry","core"]}'::jsonb),
  ('bear-hug-sandbag-carry','Bear-hug sandbag carry','bear hug sandbag carry','system',array['Sandbag']::text[],'carry','Sandbag · bilateral · carry','{"category":"strength","difficultyTier":"foundation","cautionTags":["back"],"traitTags":["carry","loaded","front_loaded"],"preferenceTags":["sandbag","carry","general fitness"]}'::jsonb),
  ('zercher-carry','Zercher carry','zercher carry','system',array['Barbell']::text[],'carry','Barbell · bilateral · carry','{"category":"strength","difficultyTier":"intermediate","cautionTags":["back"],"traitTags":["carry","loaded","front_loaded"],"preferenceTags":["barbell","carry","core","strength"]}'::jsonb),
  ('trap-bar-carry','Trap-bar carry','trap bar carry','system',array['Trap bar']::text[],'carry','Trap bar · bilateral · carry','{"category":"strength","difficultyTier":"foundation","cautionTags":["back"],"traitTags":["carry","loaded","grip"],"preferenceTags":["trap bar","carry","grip","strength"]}'::jsonb),
  ('single-arm-waiter-carry','Single-arm waiter carry','single arm waiter carry','system',array['Kettlebell','Dumbbells']::text[],'carry','Kettlebell/Dumbbells · same each side · carry','{"category":"strength","difficultyTier":"intermediate","cautionTags":["shoulder","overhead","back"],"traitTags":["carry","loaded","unilateral","overhead"],"preferenceTags":["kettlebell","dumbbells","carry","shoulder stability"]}'::jsonb),
  ('standing-cable-hip-adduction','Standing cable hip adduction','standing cable hip adduction','system',array['Cable','Ankle strap']::text[],'lateral','Cable/Ankle strap · same each side · lateral','{"category":"strength","difficultyTier":"foundation","cautionTags":["knee"],"traitTags":["unilateral","loaded","adductor"],"preferenceTags":["cable","adductors","single leg"]}'::jsonb),
  ('side-lying-hip-adduction','Side-lying hip adduction','side lying hip adduction','system',array['Bodyweight']::text[],'lateral','Bodyweight · same each side · lateral','{"category":"recovery","difficultyTier":"intro","cautionTags":["knee"],"traitTags":["unilateral","bodyweight","adductor"],"preferenceTags":["bodyweight","adductors","home"]}'::jsonb),
  ('slider-adductor-slide-out','Slider adductor slide-out','slider adductor slide out','system',array['Sliders']::text[],'lateral','Sliders · same each side · lateral','{"category":"strength","difficultyTier":"intermediate","cautionTags":["knee"],"traitTags":["unilateral","bodyweight","adductor","eccentric"],"preferenceTags":["sliders","adductors","sport"]}'::jsonb),
  ('single-arm-kettlebell-clean','Single-arm kettlebell clean','single arm kettlebell clean','system',array['Kettlebell']::text[],'power','Kettlebell · same each side · power','{"category":"athletic","difficultyTier":"foundation","cautionTags":["shoulder","back"],"traitTags":["power","loaded","unilateral","kettlebell_skill"],"preferenceTags":["kettlebell","power","single arm"]}'::jsonb),
  ('double-kettlebell-clean','Double-kettlebell clean','double kettlebell clean','system',array['Kettlebell']::text[],'power','Kettlebell · bilateral · power','{"category":"athletic","difficultyTier":"intermediate","cautionTags":["shoulder","back"],"traitTags":["power","loaded","bilateral","kettlebell_skill"],"preferenceTags":["kettlebell","power","conditioning"]}'::jsonb),
  ('single-arm-kettlebell-snatch','Single-arm kettlebell snatch','single arm kettlebell snatch','system',array['Kettlebell']::text[],'power','Kettlebell · same each side · power','{"category":"athletic","difficultyTier":"intermediate","cautionTags":["shoulder","overhead","back"],"traitTags":["power","loaded","unilateral","overhead"],"preferenceTags":["kettlebell","power","single arm","overhead"]}'::jsonb),
  ('turkish-get-up','Turkish get-up','turkish get up','system',array['Kettlebell','Dumbbells']::text[],'core','Kettlebell/Dumbbells · same each side · core','{"category":"athletic","difficultyTier":"intermediate","cautionTags":["shoulder","overhead","back","knee"],"traitTags":["full_body","loaded","unilateral","floor_transfer"],"preferenceTags":["kettlebell","core","shoulder stability"]}'::jsonb),
  ('barbell-power-clean','Barbell power clean','barbell power clean','system',array['Barbell']::text[],'power','Barbell · bilateral · power','{"category":"athletic","difficultyTier":"intermediate","cautionTags":["back","shoulder","loaded_spine"],"traitTags":["power","higher_load","olympic_derivative"],"preferenceTags":["barbell","power","sport"]}'::jsonb),
  ('hang-power-clean','Hang power clean','hang power clean','system',array['Barbell']::text[],'power','Barbell · bilateral · power','{"category":"athletic","difficultyTier":"intermediate","cautionTags":["back","shoulder","loaded_spine"],"traitTags":["power","higher_load","olympic_derivative"],"preferenceTags":["barbell","power","sport"]}'::jsonb),
  ('barbell-clean-pull','Barbell clean pull','barbell clean pull','system',array['Barbell']::text[],'power','Barbell · bilateral · power','{"category":"athletic","difficultyTier":"intermediate","cautionTags":["back","loaded_spine"],"traitTags":["power","higher_load","olympic_derivative"],"preferenceTags":["barbell","power","posterior chain"]}'::jsonb),
  ('barbell-high-pull','Barbell high pull','barbell high pull','system',array['Barbell']::text[],'power','Barbell · bilateral · power','{"category":"athletic","difficultyTier":"intermediate","cautionTags":["back","shoulder","loaded_spine"],"traitTags":["power","higher_load","olympic_derivative"],"preferenceTags":["barbell","power","upper body"]}'::jsonb),
  ('dumbbell-hang-power-clean','Dumbbell hang power clean','dumbbell hang power clean','system',array['Dumbbells']::text[],'power','Dumbbells · bilateral · power','{"category":"athletic","difficultyTier":"foundation","cautionTags":["back","shoulder"],"traitTags":["power","loaded","bilateral"],"preferenceTags":["dumbbells","power","sport"]}'::jsonb),
  ('jump-rope','Jump rope','jump rope','system',array['Jump rope']::text[],'power','Jump rope · bilateral · power','{"category":"cardio","difficultyTier":"foundation","cautionTags":["ankle","knee","impact"],"traitTags":["cardio","elastic","low_setup"],"preferenceTags":["jump rope","cardio","home"]}'::jsonb),
  ('ski-ergometer','Ski ergometer','ski ergometer','system',array['Ski ergometer']::text[],'run','Ski ergometer · bilateral · run','{"category":"cardio","difficultyTier":"foundation","cautionTags":["shoulder","back"],"traitTags":["cardio","machine","full_body"],"preferenceTags":["ski erg","cardio","conditioning"]}'::jsonb),
  ('battle-rope-alternating-waves','Battle-rope alternating waves','battle rope alternating waves','system',array['Battle ropes']::text[],'power','Battle ropes · bilateral · power','{"category":"cardio","difficultyTier":"foundation","cautionTags":["shoulder","back"],"traitTags":["cardio","upper_body","interval"],"preferenceTags":["battle ropes","conditioning","upper body"]}'::jsonb),
  ('battle-rope-slams','Battle-rope slams','battle rope slams','system',array['Battle ropes']::text[],'power','Battle ropes · bilateral · power','{"category":"cardio","difficultyTier":"foundation","cautionTags":["shoulder","overhead","back"],"traitTags":["cardio","full_body","interval"],"preferenceTags":["battle ropes","conditioning","power"]}'::jsonb),
  ('hand-over-hand-sled-pull','Hand-over-hand sled pull','hand over hand sled pull','system',array['Sled','Rope']::text[],'pull','Sled/Rope · bilateral · pull','{"category":"athletic","difficultyTier":"foundation","cautionTags":["back","shoulder"],"traitTags":["conditioning","loaded","upper_body"],"preferenceTags":["sled","rope","conditioning","pull"]}'::jsonb)
)
select 'missing_or_mismatched_issue98_identities' check_name, count(*) affected_rows
from expected e left join public.exercise_identities i on i.id = e.id
where i.id is null or i.owner_scope <> 'system' or not i.active or i.superseded_by is not null
   or (i.display_name, i.normalized_lookup_key, i.equipment_tags, i.movement_pattern, i.qualifier_text, i.metadata)
      is distinct from (e.display_name, e.normalized_lookup_key, e.equipment_tags, e.movement_pattern, e.qualifier_text, e.metadata)
union all
select 'canonical_name_collisions', count(*)
from expected e join public.exercise_identities i on i.normalized_lookup_key = e.normalized_lookup_key
where i.active and i.id <> e.id
union all
select 'reviewed_alias_collisions', count(*)
from expected e join public.exercise_aliases a on a.normalized_lookup_key = e.normalized_lookup_key
where a.reviewed
union all
select 'unexpected_user_ownership', count(*)
from expected e join public.exercise_identities i on i.id = e.id
where i.owner_scope <> 'system';
