-- Issue #69 follow-up: additive exercise catalog identity expansion and reviewed aliases.
-- Hosted status: not applied by Codex. Apply only through the normal Supabase migration flow.

insert into public.exercise_identities (id, display_name, normalized_lookup_key, owner_scope, equipment_tags, movement_pattern, qualifier_text, metadata)
values
  ('bodyweight-squat','Bodyweight squat','bodyweight squat','system',array['Bodyweight']::text[],'squat','Bodyweight · bilateral · squat','{"category":"strength","difficultyTier":"intro","cautionTags":["knee"],"traitTags":["bilateral","low_setup"],"preferenceTags":["bodyweight","lower body","squat"]}'::jsonb),
  ('box-squat','Box squat','box squat','system',array['Bodyweight','Bench']::text[],'squat','Bodyweight/Bench · bilateral · squat','{"category":"recovery","difficultyTier":"intro","cautionTags":["knee"],"traitTags":["bilateral","low_load"],"preferenceTags":["bodyweight","lower body","squat"]}'::jsonb),
  ('goblet-squat','Goblet squat','goblet squat','system',array['Dumbbells','Kettlebell']::text[],'squat','Dumbbells/Kettlebell · bilateral · squat','{"category":"strength","difficultyTier":"foundation","cautionTags":["knee","back"],"traitTags":["bilateral","loaded"],"preferenceTags":["dumbbells","kettlebell","lower body","squat"]}'::jsonb),
  ('barbell-back-squat','Barbell back squat','barbell back squat','system',array['Barbell']::text[],'squat','Barbell · bilateral · squat','{"category":"strength","difficultyTier":"intermediate","cautionTags":["knee","back","loaded_spine"],"traitTags":["bilateral","higher_load"],"preferenceTags":["barbell","lower body","squat"]}'::jsonb),
  ('romanian-deadlift','Romanian deadlift','romanian deadlift','system',array['Dumbbells','Barbell']::text[],'hinge','Dumbbells/Barbell · bilateral · hinge','{"category":"strength","difficultyTier":"foundation","cautionTags":["back","hamstring"],"traitTags":["bilateral","loaded"],"preferenceTags":["dumbbells","barbell","hinge","posterior chain"]}'::jsonb),
  ('hip-hinge-drill','Hip hinge drill','hip hinge drill','system',array['Bodyweight']::text[],'hinge','Bodyweight · bilateral · hinge','{"category":"recovery","difficultyTier":"intro","cautionTags":["back","hamstring"],"traitTags":["low_load","technique"],"preferenceTags":["bodyweight","hinge","posterior chain"]}'::jsonb),
  ('glute-bridge','Glute bridge','glute bridge','system',array['Bodyweight','Bands']::text[],'hinge','Bodyweight/Bands · bilateral · hinge','{"category":"recovery","difficultyTier":"intro","cautionTags":[],"traitTags":["low_load","posterior_chain"],"preferenceTags":["bodyweight","glutes","lower body"]}'::jsonb),
  ('reverse-lunge','Reverse lunge','reverse lunge','system',array['Bodyweight','Dumbbells']::text[],'lunge','Bodyweight/Dumbbells · same each side · lunge','{"category":"strength","difficultyTier":"foundation","cautionTags":["knee"],"traitTags":["unilateral","lower_body"],"preferenceTags":["bodyweight","dumbbells","lower body","lunge"]}'::jsonb),
  ('step-up','Step-up','step up','system',array['Bodyweight','Dumbbells','Bench']::text[],'lunge','Bodyweight/Dumbbells/Bench · same each side · lunge','{"category":"strength","difficultyTier":"foundation","cautionTags":["knee"],"traitTags":["unilateral","lower_body"],"preferenceTags":["bodyweight","dumbbells","lower body","running prep"]}'::jsonb),
  ('walking-lunge','Walking lunge','walking lunge','system',array['Bodyweight','Dumbbells']::text[],'lunge','Bodyweight/Dumbbells · same each side · lunge','{"category":"running_prep","difficultyTier":"foundation","cautionTags":["knee"],"traitTags":["unilateral","running_support"],"preferenceTags":["bodyweight","dumbbells","lower body","running prep"]}'::jsonb),
  ('incline-push-up','Incline push-up','incline push up','system',array['Bodyweight','Bench']::text[],'push','Bodyweight/Bench · bilateral · push','{"category":"strength","difficultyTier":"intro","cautionTags":["shoulder"],"traitTags":["upper_body","low_load"],"preferenceTags":["bodyweight","push","upper body"]}'::jsonb),
  ('push-up','Push-up','push up','system',array['Bodyweight']::text[],'push','Bodyweight · bilateral · push','{"category":"strength","difficultyTier":"foundation","cautionTags":["shoulder"],"traitTags":["upper_body","low_setup"],"preferenceTags":["bodyweight","push","upper body"]}'::jsonb),
  ('dumbbell-floor-press','Dumbbell floor press','dumbbell floor press','system',array['Dumbbells']::text[],'push','Dumbbells · bilateral · push','{"category":"strength","difficultyTier":"foundation","cautionTags":["shoulder"],"traitTags":["upper_body","loaded"],"preferenceTags":["dumbbells","push","chest","upper body"]}'::jsonb),
  ('dumbbell-shoulder-press','Dumbbell shoulder press','dumbbell shoulder press','system',array['Dumbbells']::text[],'push','Dumbbells · bilateral · push','{"category":"strength","difficultyTier":"foundation","cautionTags":["shoulder","overhead"],"traitTags":["upper_body","loaded"],"preferenceTags":["dumbbells","push","shoulders","overhead"]}'::jsonb),
  ('band-row','Band row','band row','system',array['Bands']::text[],'pull','Bands · bilateral · pull','{"category":"strength","difficultyTier":"intro","cautionTags":["shoulder"],"traitTags":["upper_body","low_load"],"preferenceTags":["bands","pull","upper body","back"]}'::jsonb),
  ('dumbbell-row','Dumbbell row','dumbbell row','system',array['Dumbbells','Bench']::text[],'pull','Dumbbells/Bench · same each side · pull','{"category":"strength","difficultyTier":"foundation","cautionTags":["shoulder","back"],"traitTags":["upper_body","loaded"],"preferenceTags":["dumbbells","pull","upper body","back"]}'::jsonb),
  ('farmer-carry','Farmer carry','farmer carry','system',array['Dumbbells','Kettlebell']::text[],'carry','Dumbbells/Kettlebell · bilateral · carry','{"category":"strength","difficultyTier":"foundation","cautionTags":["back"],"traitTags":["loaded","core","grip"],"preferenceTags":["dumbbells","kettlebell","carry","core"]}'::jsonb),
  ('dead-bug','Dead bug','dead bug','system',array['Bodyweight']::text[],'core','Bodyweight · same each side · core','{"category":"core","difficultyTier":"intro","cautionTags":[],"traitTags":["core","low_load"],"preferenceTags":["bodyweight","core"]}'::jsonb),
  ('side-plank','Side plank','side plank','system',array['Bodyweight']::text[],'core','Bodyweight · same each side · core','{"category":"core","difficultyTier":"foundation","cautionTags":["shoulder"],"traitTags":["core","lateral"],"preferenceTags":["bodyweight","core"]}'::jsonb),
  ('bird-dog','Bird dog','bird dog','system',array['Bodyweight']::text[],'core','Bodyweight · bilateral · core','{"category":"core","difficultyTier":"intro","cautionTags":[],"traitTags":["core","low_load"],"preferenceTags":["bodyweight","core","back-friendly"]}'::jsonb),
  ('dumbbell-lateral-raise','Dumbbell lateral raise','dumbbell lateral raise','system',array['Dumbbells']::text[],'push','Dumbbells · bilateral · push','{"category":"strength","difficultyTier":"foundation","cautionTags":["shoulder"],"traitTags":["upper_body","accessory"],"preferenceTags":["dumbbells","shoulders","hypertrophy"]}'::jsonb),
  ('dumbbell-curl','Dumbbell curl','dumbbell curl','system',array['Dumbbells']::text[],'pull','Dumbbells · bilateral · pull','{"category":"strength","difficultyTier":"intro","cautionTags":[],"traitTags":["upper_body","accessory"],"preferenceTags":["dumbbells","arms","hypertrophy"]}'::jsonb),
  ('calf-raise','Calf raise','calf raise','system',array['Bodyweight','Dumbbells']::text[],'calf','Bodyweight/Dumbbells · bilateral · calf','{"category":"running_prep","difficultyTier":"intro","cautionTags":["ankle"],"traitTags":["lower_body","running_support"],"preferenceTags":["bodyweight","dumbbells","calves","running prep"]}'::jsonb),
  ('tibialis-raise','Tibialis raise','tibialis raise','system',array['Bodyweight']::text[],'calf','Bodyweight · bilateral · calf','{"category":"running_prep","difficultyTier":"intro","cautionTags":["ankle"],"traitTags":["lower_body","running_support"],"preferenceTags":["bodyweight","shin","running prep"]}'::jsonb),
  ('hip-flexor-rockback','Hip flexor rockback','hip flexor rockback','system',array['Bodyweight']::text[],'mobility','Bodyweight · same each side · mobility','{"category":"mobility","difficultyTier":"intro","cautionTags":[],"traitTags":["mobility","low_load"],"preferenceTags":["bodyweight","mobility","hips"]}'::jsonb),
  ('thoracic-rotation','Thoracic rotation','thoracic rotation','system',array['Bodyweight']::text[],'mobility','Bodyweight · same each side · mobility','{"category":"mobility","difficultyTier":"intro","cautionTags":[],"traitTags":["mobility","upper_body"],"preferenceTags":["bodyweight","mobility","upper back"]}'::jsonb),
  ('ankle-rock','Ankle rock','ankle rock','system',array['Bodyweight']::text[],'mobility','Bodyweight · same each side · mobility','{"category":"mobility","difficultyTier":"intro","cautionTags":["ankle"],"traitTags":["mobility","running_support"],"preferenceTags":["bodyweight","mobility","ankle","running prep"]}'::jsonb),
  ('brisk-walk','Brisk walk','brisk walk','system',array['Bodyweight']::text[],'walk','Bodyweight · bilateral · walk','{"category":"cardio","difficultyTier":"intro","cautionTags":[],"traitTags":["cardio","low_setup","low_impact"],"preferenceTags":["cardio","walking","outdoors","bodyweight"]}'::jsonb),
  ('low-impact-cardio-march','Low-impact cardio march','low impact cardio march','system',array['Bodyweight']::text[],'walk','Bodyweight · bilateral · walk','{"category":"cardio","difficultyTier":"intro","cautionTags":[],"traitTags":["cardio","low_setup","low_impact"],"preferenceTags":["cardio","bodyweight","home"]}'::jsonb),
  ('run-walk-intervals','Run/walk intervals','run walk intervals','system',array['Bodyweight']::text[],'run','Bodyweight · bilateral · run','{"category":"cardio","difficultyTier":"intro","cautionTags":["impact","knee","ankle"],"traitTags":["running","interval","cardio"],"preferenceTags":["running","cardio","outdoors"]}'::jsonb),
  ('easy-run','Easy run','easy run','system',array['Bodyweight']::text[],'run','Bodyweight · bilateral · run','{"category":"cardio","difficultyTier":"foundation","cautionTags":["impact","knee","ankle"],"traitTags":["running","cardio"],"preferenceTags":["running","cardio","outdoors"]}'::jsonb),
  ('stride-drills','Stride drills','stride drills','system',array['Bodyweight']::text[],'run','Bodyweight · bilateral · run','{"category":"running_prep","difficultyTier":"foundation","cautionTags":["impact","knee","ankle","hamstring"],"traitTags":["running","speed","athletic"],"preferenceTags":["running","cardio","sport"]}'::jsonb),
  ('lateral-lunge','Lateral lunge','lateral lunge','system',array['Bodyweight','Dumbbells']::text[],'lateral','Bodyweight/Dumbbells · same each side · lateral','{"category":"athletic","difficultyTier":"foundation","cautionTags":["knee"],"traitTags":["unilateral","lateral","athletic"],"preferenceTags":["sport","lateral","lower body"]}'::jsonb),
  ('lateral-shuffle','Lateral shuffle','lateral shuffle','system',array['Bodyweight']::text[],'lateral','Bodyweight · bilateral · lateral','{"category":"athletic","difficultyTier":"foundation","cautionTags":["knee","ankle","impact"],"traitTags":["lateral","athletic","cardio"],"preferenceTags":["sport","lateral","agility"]}'::jsonb),
  ('skater-hop','Skater hop','skater hop','system',array['Bodyweight']::text[],'power','Bodyweight · same each side · power','{"category":"athletic","difficultyTier":"intermediate","cautionTags":["knee","ankle","impact"],"traitTags":["unilateral","lateral","power","athletic"],"preferenceTags":["sport","lateral","jumping","power"]}'::jsonb),
  ('front-squat','Front squat','front squat','system',array['Barbell']::text[],'squat','Barbell · bilateral · squat','{"category":"strength","difficultyTier":"intermediate","cautionTags":["knee","back","loaded_spine"],"traitTags":["bilateral","loaded"],"preferenceTags":["barbell","lower body","squat"]}'::jsonb),
  ('dumbbell-squat','Dumbbell squat','dumbbell squat','system',array['Dumbbells']::text[],'squat','Dumbbells · bilateral · squat','{"category":"strength","difficultyTier":"foundation","cautionTags":["knee","back"],"traitTags":["bilateral","loaded"],"preferenceTags":["dumbbells","lower body","squat"]}'::jsonb),
  ('leg-press','Leg press','leg press','system',array['Machine']::text[],'squat','Machine · bilateral · squat','{"category":"strength","difficultyTier":"foundation","cautionTags":["knee","back"],"traitTags":["bilateral","machine"],"preferenceTags":["machine","lower body","squat"]}'::jsonb),
  ('leg-extension','Leg extension','leg extension','system',array['Machine']::text[],'squat','Machine · bilateral · squat','{"category":"strength","difficultyTier":"foundation","cautionTags":["knee"],"traitTags":["machine","accessory"],"preferenceTags":["machine","quads","hypertrophy"]}'::jsonb),
  ('split-squat','Split squat','split squat','system',array['Bodyweight','Dumbbells']::text[],'lunge','Bodyweight/Dumbbells · same each side · lunge','{"category":"strength","difficultyTier":"foundation","cautionTags":["knee"],"traitTags":["unilateral","lower_body"],"preferenceTags":["bodyweight","dumbbells","lower body","lunge"]}'::jsonb),
  ('bulgarian-split-squat','Bulgarian split squat','bulgarian split squat','system',array['Bodyweight','Dumbbells','Bench']::text[],'lunge','Bodyweight/Dumbbells/Bench · same each side · lunge','{"category":"strength","difficultyTier":"intermediate","cautionTags":["knee"],"traitTags":["unilateral","lower_body"],"preferenceTags":["dumbbells","lower body","lunge"]}'::jsonb),
  ('forward-lunge','Forward lunge','forward lunge','system',array['Bodyweight','Dumbbells']::text[],'lunge','Bodyweight/Dumbbells · same each side · lunge','{"category":"strength","difficultyTier":"foundation","cautionTags":["knee"],"traitTags":["unilateral","lower_body"],"preferenceTags":["bodyweight","dumbbells","lower body","lunge"]}'::jsonb),
  ('conventional-deadlift','Conventional deadlift','conventional deadlift','system',array['Barbell']::text[],'hinge','Barbell · bilateral · hinge','{"category":"strength","difficultyTier":"intermediate","cautionTags":["back","hamstring","loaded_spine"],"traitTags":["bilateral","higher_load"],"preferenceTags":["barbell","hinge","posterior chain"]}'::jsonb),
  ('trap-bar-deadlift','Trap-bar deadlift','trap bar deadlift','system',array['Trap bar']::text[],'hinge','Trap bar · bilateral · hinge','{"category":"strength","difficultyTier":"foundation","cautionTags":["back","loaded_spine"],"traitTags":["bilateral","loaded"],"preferenceTags":["trap bar","hinge","lower body"]}'::jsonb),
  ('dumbbell-romanian-deadlift','Dumbbell Romanian deadlift','dumbbell romanian deadlift','system',array['Dumbbells']::text[],'hinge','Dumbbells · bilateral · hinge','{"category":"strength","difficultyTier":"foundation","cautionTags":["back","hamstring"],"traitTags":["bilateral","loaded"],"preferenceTags":["dumbbells","hinge","posterior chain"]}'::jsonb),
  ('hip-thrust','Hip thrust','hip thrust','system',array['Barbell','Bench']::text[],'hinge','Barbell/Bench · bilateral · hinge','{"category":"strength","difficultyTier":"foundation","cautionTags":["back"],"traitTags":["bilateral","loaded"],"preferenceTags":["barbell","glutes","posterior chain"]}'::jsonb),
  ('back-extension','Back extension','back extension','system',array['Machine']::text[],'hinge','Machine · bilateral · hinge','{"category":"strength","difficultyTier":"foundation","cautionTags":["back","hamstring"],"traitTags":["posterior_chain","machine"],"preferenceTags":["posterior chain","back","glutes"]}'::jsonb),
  ('seated-leg-curl','Seated leg curl','seated leg curl','system',array['Machine']::text[],'hinge','Machine · bilateral · hinge','{"category":"strength","difficultyTier":"foundation","cautionTags":["hamstring","knee"],"traitTags":["machine","accessory"],"preferenceTags":["machine","hamstrings","hypertrophy"]}'::jsonb),
  ('barbell-bench-press','Barbell bench press','barbell bench press','system',array['Barbell','Bench']::text[],'push','Barbell/Bench · bilateral · push','{"category":"strength","difficultyTier":"intermediate","cautionTags":["shoulder"],"traitTags":["upper_body","higher_load"],"preferenceTags":["barbell","chest","push"]}'::jsonb),
  ('dumbbell-bench-press','Dumbbell bench press','dumbbell bench press','system',array['Dumbbells','Bench']::text[],'push','Dumbbells/Bench · bilateral · push','{"category":"strength","difficultyTier":"foundation","cautionTags":["shoulder"],"traitTags":["upper_body","loaded"],"preferenceTags":["dumbbells","chest","push"]}'::jsonb),
  ('incline-dumbbell-press','Incline dumbbell press','incline dumbbell press','system',array['Dumbbells','Bench']::text[],'push','Dumbbells/Bench · bilateral · push','{"category":"strength","difficultyTier":"foundation","cautionTags":["shoulder"],"traitTags":["upper_body","loaded"],"preferenceTags":["dumbbells","chest","push","incline"]}'::jsonb),
  ('machine-chest-press','Machine chest press','machine chest press','system',array['Machine']::text[],'push','Machine · bilateral · push','{"category":"strength","difficultyTier":"foundation","cautionTags":["shoulder"],"traitTags":["upper_body","machine"],"preferenceTags":["machine","chest","push"]}'::jsonb),
  ('barbell-overhead-press','Barbell overhead press','barbell overhead press','system',array['Barbell']::text[],'push','Barbell · bilateral · push','{"category":"strength","difficultyTier":"intermediate","cautionTags":["shoulder","overhead","back"],"traitTags":["upper_body","loaded"],"preferenceTags":["barbell","shoulders","overhead"]}'::jsonb),
  ('triceps-pushdown','Triceps pushdown','triceps pushdown','system',array['Cable']::text[],'push','Cable · bilateral · push','{"category":"strength","difficultyTier":"intro","cautionTags":["shoulder"],"traitTags":["upper_body","accessory"],"preferenceTags":["cable","arms","triceps"]}'::jsonb),
  ('seated-cable-row','Seated cable row','seated cable row','system',array['Cable']::text[],'pull','Cable · bilateral · pull','{"category":"strength","difficultyTier":"foundation","cautionTags":["shoulder","back"],"traitTags":["upper_body","loaded"],"preferenceTags":["cable","back","pull"]}'::jsonb),
  ('chest-supported-row','Chest-supported row','chest supported row','system',array['Dumbbells','Bench']::text[],'pull','Dumbbells/Bench · bilateral · pull','{"category":"strength","difficultyTier":"foundation","cautionTags":["shoulder"],"traitTags":["upper_body","supported"],"preferenceTags":["dumbbells","back","pull"]}'::jsonb),
  ('barbell-row','Barbell row','barbell row','system',array['Barbell']::text[],'pull','Barbell · bilateral · pull','{"category":"strength","difficultyTier":"intermediate","cautionTags":["back","shoulder"],"traitTags":["upper_body","loaded"],"preferenceTags":["barbell","back","pull"]}'::jsonb),
  ('lat-pulldown','Lat pulldown','lat pulldown','system',array['Cable','Machine']::text[],'pull','Cable/Machine · bilateral · pull','{"category":"strength","difficultyTier":"foundation","cautionTags":["shoulder"],"traitTags":["upper_body","machine"],"preferenceTags":["cable","machine","back","pull"]}'::jsonb),
  ('pull-up','Pull-up','pull up','system',array['Pull-up bar']::text[],'pull','Pull-up bar · bilateral · pull','{"category":"strength","difficultyTier":"intermediate","cautionTags":["shoulder"],"traitTags":["upper_body","bodyweight"],"preferenceTags":["bodyweight","back","pull"]}'::jsonb),
  ('assisted-pull-up','Assisted pull-up','assisted pull up','system',array['Machine','Bands','Pull-up bar']::text[],'pull','Machine/Bands/Pull-up bar · bilateral · pull','{"category":"strength","difficultyTier":"foundation","cautionTags":["shoulder"],"traitTags":["upper_body","assisted"],"preferenceTags":["bodyweight","back","pull"]}'::jsonb),
  ('face-pull','Face pull','face pull','system',array['Cable','Bands']::text[],'pull','Cable/Bands · bilateral · pull','{"category":"strength","difficultyTier":"intro","cautionTags":["shoulder"],"traitTags":["upper_body","accessory"],"preferenceTags":["cable","bands","shoulders","pull"]}'::jsonb),
  ('reverse-fly','Reverse fly','reverse fly','system',array['Dumbbells']::text[],'pull','Dumbbells · bilateral · pull','{"category":"strength","difficultyTier":"intro","cautionTags":["shoulder"],"traitTags":["upper_body","accessory"],"preferenceTags":["dumbbells","rear delts","pull"]}'::jsonb),
  ('suitcase-carry','Suitcase carry','suitcase carry','system',array['Dumbbells','Kettlebell']::text[],'carry','Dumbbells/Kettlebell · same each side · carry','{"category":"strength","difficultyTier":"foundation","cautionTags":["back"],"traitTags":["loaded","core","grip","unilateral_load"],"preferenceTags":["dumbbells","kettlebell","carry","core"]}'::jsonb),
  ('plank','Plank','plank','system',array['Bodyweight']::text[],'core','Bodyweight · bilateral · core','{"category":"core","difficultyTier":"intro","cautionTags":["shoulder","back"],"traitTags":["core","anti_extension"],"preferenceTags":["bodyweight","core"]}'::jsonb),
  ('pallof-press','Pallof press','pallof press','system',array['Cable','Bands']::text[],'core','Cable/Bands · same each side · core','{"category":"core","difficultyTier":"foundation","cautionTags":[],"traitTags":["core","anti_rotation"],"preferenceTags":["cable","bands","core"]}'::jsonb),
  ('inverted-row','Inverted row','inverted row','system',array['Bar','Bodyweight']::text[],'pull','Bar/Bodyweight · bilateral · pull','{"category":"strength","difficultyTier":"foundation","cautionTags":["shoulder"],"traitTags":["upper_body","bodyweight"],"preferenceTags":["bodyweight","back","pull"]}'::jsonb),
  ('wall-sit','Wall sit','wall sit','system',array['Bodyweight']::text[],'squat','Bodyweight · bilateral · squat','{"category":"strength","difficultyTier":"intro","cautionTags":["knee"],"traitTags":["lower_body","isometric"],"preferenceTags":["bodyweight","quads","lower body"]}'::jsonb),
  ('calf-stretch','Calf stretch','calf stretch','system',array['Bodyweight','Wall']::text[],'mobility','Bodyweight/Wall · same each side · mobility','{"category":"mobility","difficultyTier":"intro","cautionTags":["ankle"],"traitTags":["mobility","low_load"],"preferenceTags":["mobility","calves","running prep"]}'::jsonb),
  ('shoulder-wall-slide','Shoulder wall slide','shoulder wall slide','system',array['Bodyweight','Wall']::text[],'mobility','Bodyweight/Wall · bilateral · mobility','{"category":"mobility","difficultyTier":"intro","cautionTags":["shoulder"],"traitTags":["mobility","upper_body"],"preferenceTags":["mobility","shoulders"]}'::jsonb),
  ('marching-drill','Marching drill','marching drill','system',array['Bodyweight']::text[],'run','Bodyweight · bilateral · run','{"category":"running_prep","difficultyTier":"intro","cautionTags":[],"traitTags":["running_support","low_impact"],"preferenceTags":["running prep","bodyweight"]}'::jsonb),
  ('pogo-hop','Pogo hop','pogo hop','system',array['Bodyweight']::text[],'power','Bodyweight · bilateral · power','{"category":"running_prep","difficultyTier":"foundation","cautionTags":["impact","ankle","knee"],"traitTags":["running_support","power"],"preferenceTags":["running prep","plyometric"]}'::jsonb)
on conflict (id) do update set
  display_name = excluded.display_name,
  normalized_lookup_key = excluded.normalized_lookup_key,
  equipment_tags = excluded.equipment_tags,
  movement_pattern = excluded.movement_pattern,
  qualifier_text = excluded.qualifier_text,
  metadata = excluded.metadata,
  updated_at = now()
where public.exercise_identities.owner_scope = 'system';

insert into public.exercise_aliases (exercise_identity_id, alias, normalized_lookup_key, owner_scope, reviewed)
values
  ('push-up','push up','push up','system',true),
  ('push-up','pushup','pushup','system',true),
  ('push-up','press up','press up','system',true),
  ('push-up','push ups','push ups','system',true),
  ('romanian-deadlift','rdl','rdl','system',true),
  ('romanian-deadlift','romanian dead lift','romanian dead lift','system',true),
  ('romanian-deadlift','romanian deadlifts','romanian deadlifts','system',true),
  ('bodyweight-squat','bodyweight squat','bodyweight squat','system',true),
  ('bodyweight-squat','air squat','air squat','system',true),
  ('bodyweight-squat','bodyweight squats','bodyweight squats','system',true),
  ('goblet-squat','goblet squats','goblet squats','system',true),
  ('goblet-squat','kb goblet squat','kb goblet squat','system',true),
  ('goblet-squat','db goblet squat','db goblet squat','system',true),
  ('dumbbell-row','db row','db row','system',true),
  ('dumbbell-row','dumbbell row','dumbbell row','system',true),
  ('dumbbell-row','one arm dumbbell row','one arm dumbbell row','system',true),
  ('dumbbell-row','single arm dumbbell row','single arm dumbbell row','system',true),
  ('dumbbell-bench-press','db bench press','db bench press','system',true),
  ('dumbbell-bench-press','dumbbell bench','dumbbell bench','system',true),
  ('dumbbell-bench-press','db bench','db bench','system',true),
  ('dumbbell-bench-press','dumbbell chest press','dumbbell chest press','system',true),
  ('barbell-bench-press','bb bench press','bb bench press','system',true),
  ('barbell-bench-press','bench press','bench press','system',true),
  ('barbell-bench-press','barbell bench','barbell bench','system',true),
  ('dumbbell-romanian-deadlift','db rdl','db rdl','system',true),
  ('dumbbell-romanian-deadlift','dumbbell rdl','dumbbell rdl','system',true),
  ('dumbbell-romanian-deadlift','dumbbell romanian deadlifts','dumbbell romanian deadlifts','system',true),
  ('barbell-overhead-press','bb overhead press','bb overhead press','system',true),
  ('barbell-overhead-press','barbell shoulder press','barbell shoulder press','system',true),
  ('barbell-overhead-press','overhead press','overhead press','system',true),
  ('barbell-overhead-press','ohp','ohp','system',true),
  ('dumbbell-shoulder-press','db shoulder press','db shoulder press','system',true),
  ('dumbbell-shoulder-press','dumbbell overhead press','dumbbell overhead press','system',true),
  ('dumbbell-shoulder-press','db overhead press','db overhead press','system',true),
  ('seated-cable-row','cable row','cable row','system',true),
  ('seated-cable-row','seated row','seated row','system',true),
  ('lat-pulldown','lat pull down','lat pull down','system',true),
  ('lat-pulldown','pulldown','pulldown','system',true),
  ('lat-pulldown','lat pulldowns','lat pulldowns','system',true),
  ('triceps-pushdown','tricep pushdown','tricep pushdown','system',true),
  ('triceps-pushdown','cable triceps pushdown','cable triceps pushdown','system',true),
  ('triceps-pushdown','triceps pressdown','triceps pressdown','system',true),
  ('calf-raise','calf raises','calf raises','system',true),
  ('calf-raise','standing calf raise','standing calf raise','system',true),
  ('plank','front plank','front plank','system',true),
  ('side-plank','side plank hold','side plank hold','system',true),
  ('pallof-press','pallof presses','pallof presses','system',true),
  ('farmer-carry','farmer walk','farmer walk','system',true),
  ('suitcase-carry','suitcase walk','suitcase walk','system',true),
  ('leg-extension','leg extensions','leg extensions','system',true),
  ('seated-leg-curl','seated hamstring curl','seated hamstring curl','system',true),
  ('seated-leg-curl','hamstring curl machine','hamstring curl machine','system',true),
  ('split-squat','split squats','split squats','system',true),
  ('bulgarian-split-squat','rear foot elevated split squat','rear foot elevated split squat','system',true),
  ('bulgarian-split-squat','rfess','rfess','system',true),
  ('forward-lunge','forward lunges','forward lunges','system',true),
  ('reverse-lunge','reverse lunges','reverse lunges','system',true),
  ('walking-lunge','walking lunges','walking lunges','system',true)
on conflict (normalized_lookup_key) where owner_scope = 'system' and reviewed do update set
  exercise_identity_id = excluded.exercise_identity_id,
  alias = excluded.alias,
  updated_at = now()
where public.exercise_aliases.owner_scope = 'system' and public.exercise_aliases.reviewed;
